#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/POSItemList.cshtml")]
    public partial class _Views_Shared_POSItemList_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_POSItemList_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"category list\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cat filter\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        Clear\r\n        <i");

WriteLiteral(" class=\"delete icon\"");

WriteLiteral("></i>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"search panel\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"search\"");

WriteLiteral(" placeholder=\"Search ...\"");

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"item list\"");

WriteLiteral(" id=\"POSItemList\"");

WriteLiteral(">\r\n</div>\r\n<script>\r\n    var itemTemplate = `<div class=\"item\" id=\"pos-{ItemId}\" " +
"data-selling-price=\"{SellingPrice}\" data-photo=\"{Photo}\" data-unit-id=\"{UnitId}\"" +
" data-valid-units=\"{ValidUnits}\" data-brand=\"{BrandName}\" data-item-group=\"{Item" +
"GroupName}\" data-item-name=\"{ItemName}\" data-item-code=\"{ItemCode}\" data-item-id" +
"=\"{ItemId}\" data-price=\"{Price}\">\r\n\t<div class=\"photo block\">\r\n\t\t<img src=\"{Phot" +
"o}\">\r\n\t</div>\r\n\t<div class=\"info block\">\r\n\t\t<div class=\"header\">{ItemName}</div>" +
"\r\n\t\t<div class=\"price info\">\r\n\t\t\t<span class =\"rate\">{SellingPrice}</span>\r\n\t\t\t<" +
"span>&nbsp; x&nbsp; </span>\r\n\t\t\t<span class=\"quantity\">1</span>\r\n\t\t\t<span>&nbsp;" +
" =&nbsp; </span>\r\n\t\t\t<span class=\"amount\"></span>\r\n\t\t</div>\r\n\t\t<div class=\"disco" +
"unt info\" style=\"display:none;\">\r\n\t\t\t<span>Less&nbsp; </span>\r\n\t\t\t<span class=\"d" +
"iscount rate\"></span>\r\n\t\t\t<span>&nbsp; =&nbsp; </span>\r\n\t\t\t<span class=\"discount" +
"ed amount\"></span>\r\n\t\t</div>\r\n\t\t<div class =\"tax info\" style=\"display:none;\">\r\n\t" +
"\t\t<span>Add Tax </span>\r\n\t\t\t<span class =\"tax-amount\"></span>\r\n\t\t\t<span> (</span" +
">\r\n\t\t\t<span class =\"tax-rate\"></span>\r\n\t\t\t<span>%) = </span>\r\n\t\t\t<span class=\"am" +
"ount-plus-tax\"></span>\r\n\t\t</div>\r\n\t\t<div>\r\n\t\t\t<select class=\"unit inverted\" data" +
"-item-id=\"{ItemId}\">\r\n\t\t\t</select>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"number block" +
"\">\r\n\t\t<input type=\"text\" class =\"decimal price\" title=\"Edit Price\" value=\"{Selli" +
"ngPrice}\">\r\n\t\t<input type=\"text\" class=\"decimal quantity\" title=\"Enter Quantity\"" +
" value=\"1\">\r\n\t\t<input type=\"text\" class=\"decimal discount\" title=\"Enter Rate of " +
"Discount\" value=\"\">\r\n\t\t<button class=\"ui red fluid button\" onclick=\"removeItem(t" +
"his);\" style=\"display:none;\">Delete</button>\r\n\t</div>\r\n</div>`\r\n</script>\r\n\r\n<sc" +
"ript>\r\n    var products = [];\r\n    var metaUnits = [];\r\n\r\n    function defaulPOS" +
"ItemClick(el, callback) {\r\n        var targetEl = $(\"#SalesItems\");\r\n\r\n        $" +
"(\".tender.info.items\").hide();\r\n        $(\".footer.items\").show();\r\n        targ" +
"etEl.show();\r\n\r\n        var sellingPrice = el.attr(\"data-selling-price\");\r\n     " +
"   var photo = el.attr(\"data-photo\");\r\n\r\n        var barCode = el.attr(\"data-bar" +
"code\");\r\n        var brand = el.attr(\"data-brand\");\r\n        var unitId = el.att" +
"r(\"data-unit-id\");\r\n        var validUnits = el.attr(\"data-valid-units\");\r\n     " +
"   var itemGroup = el.attr(\"data-item-group\");\r\n        var itemName = el.attr(\"" +
"data-item-name\");\r\n        var itemCode = el.attr(\"data-item-code\");\r\n        va" +
"r itemId = el.attr(\"data-item-id\");\r\n        var isTaxableItem = el.attr(\"data-i" +
"s-taxable-item\") === \"true\";\r\n        var taxRate = window.parseFloat($(\"#SalesT" +
"axRateHidden\").val());\r\n\r\n        var price = window.parseFloat2(sellingPrice ||" +
" 0);\r\n\r\n        if (!price) {\r\n            window.displayMessage(\"Cannot add ite" +
"m because the price is zero.\");\r\n            return;\r\n        };\r\n\r\n\r\n\r\n        " +
"var selector = \"pos-\" + itemId;\r\n        var existingEl = $(\"#\" + selector);\r\n\r\n" +
"        if (existingEl.length) {\r\n            var existingQuantitySpan = existin" +
"gEl.find(\"span.quantity\");\r\n            var existingQuantityInput = existingEl.f" +
"ind(\"input.quantity\");\r\n\r\n            var quantity = window.parseFloat2(existing" +
"QuantitySpan.text() || 0);\r\n            quantity++;\r\n\r\n            existingQuant" +
"itySpan.text(quantity);\r\n            existingQuantityInput.val(quantity).trigger" +
"(\"keyup\");\r\n\r\n            window.updateTotal();\r\n            return;\r\n        };" +
"\r\n\r\n        var template = itemTemplate;\r\n\r\n        template = template.replace(" +
"/{ItemId}/g, itemId);\r\n        template = template.replace(/{SellingPrice}/g, se" +
"llingPrice);\r\n        template = template.replace(/{Photo}/g, photo);\r\n        t" +
"emplate = template.replace(/{BarCode}/g, barCode);\r\n        template = template." +
"replace(/{BrandName}/g, brand);\r\n        template = template.replace(/{ItemGroup" +
"Name}/g, itemGroup);\r\n        template = template.replace(/{ItemName}/g, itemNam" +
"e);\r\n        template = template.replace(/{ItemCode}/g, itemCode);\r\n        temp" +
"late = template.replace(/{Price}/g, price);\r\n        template = template.replace" +
"(/{UnitId}/g, unitId);\r\n        template = template.replace(/{ValidUnits}/g, val" +
"idUnits);\r\n\r\n        var item = $(template);\r\n        var quantityInput = item.f" +
"ind(\"input.quantity\");\r\n        var priceInput = item.find(\"input.price\");\r\n    " +
"    var discountInput = item.find(\"input.discount\");\r\n        var unitSelect = i" +
"tem.find(\"select.unit\");\r\n\r\n        function loadUnits(el, defaultUnitId, validU" +
"nits) {\r\n            el.html(\"\");\r\n\r\n            const units = window.Enumerable" +
".From(window.metaUnits)\r\n                .Where(function (x) {\r\n                " +
"    return validUnits.indexOf(x.UnitId.toString()) > -1;\r\n                }).ToA" +
"rray();\r\n\r\n            $.each(units, function () {\r\n                const unit =" +
" this;\r\n\r\n                const option = $(\"<option/ >\");\r\n                optio" +
"n.attr(\"value\", unit.UnitId);\r\n                option.html(unit.UnitName);\r\n\r\n  " +
"              if (defaultUnitId === unit.UnitId) {\r\n                    option.a" +
"ttr(\"selected\", \"\");\r\n                };\r\n\r\n                option.appendTo(el);" +
"\r\n            });\r\n\r\n        };\r\n\r\n        loadUnits(unitSelect, unitId, validUn" +
"its.split(\',\'));\r\n\r\n        function updateItemInfo(el) {\r\n            const qua" +
"ntityEl = el.find(\"input.quantity\");\r\n            const discountEl = el.find(\"in" +
"put.discount\");\r\n\r\n            const quantity = window.parseFloat2(quantityEl.va" +
"l() || 0);\r\n            const discountRate = window.parseFloat2(discountEl.val()" +
".replace(\"%\", \"\")) || 0;\r\n\r\n            const price = window.parseFloat2(el.find" +
"(\"input.price\").val());\r\n\r\n            const amount = window.round(price * quant" +
"ity, 2);\r\n            const discountedAmount = window.round((price * quantity) *" +
" ((100 - discountRate) / 100), 2);\r\n\r\n            el.find(\"span.rate:not(.discou" +
"nt)\").html(price);\r\n            el.find(\"span.quantity\").html(quantity);\r\n      " +
"      el.find(\"span.amount\").html(amount);\r\n            el.find(\"span.discount.r" +
"ate\").html(\"\");\r\n            el.find(\"span.discounted.amount\").html(\"\");\r\n\r\n    " +
"        el.find(\"span.discount.rate\").html(discountEl.val().replace(\"%\", \"\") + \"" +
"%\");\r\n            el.find(\"span.discounted.amount\").html(discountedAmount);\r\n\r\n " +
"           if (discountRate) {\r\n                el.find(\".discount.info\").show()" +
";\r\n            } else {\r\n                el.find(\".discount.info\").hide();\r\n    " +
"        };\r\n\r\n            if (isTaxableItem) {\r\n                const tax = wind" +
"ow.round(discountedAmount * taxRate / 100, 2);\r\n                const amountPlus" +
"Tax = window.round(discountedAmount + tax, 2);\r\n                el.find(\".tax.in" +
"fo .tax-amount\").html(tax);\r\n                el.find(\".tax.info .tax-rate\").html" +
"(window.round(taxRate, 2));\r\n                el.find(\".tax.info .amount-plus-tax" +
"\").html(amountPlusTax);\r\n                el.find(\".tax.info\").show();\r\n         " +
"   };\r\n\r\n            window.updateTotal();\r\n        };\r\n\r\n        quantityInput." +
"on(\"keyup\", function () {\r\n            const el = $(this);\r\n            const pa" +
"rentInfo = el.parent().parent();\r\n            updateItemInfo(parentInfo);\r\n     " +
"   });\r\n\r\n        discountInput.on(\"keyup\", function () {\r\n            const el " +
"= $(this);\r\n\r\n            const rate = window.parseFloat2(el.val());\r\n          " +
"  if (rate > 100) {\r\n                el.val(\"100\");\r\n                return;\r\n  " +
"          };\r\n\r\n            const parentInfo = el.parent().parent();\r\n          " +
"  updateItemInfo(parentInfo);\r\n        });\r\n\r\n        priceInput.on(\"keyup\", fun" +
"ction () {\r\n            const el = $(this);\r\n            const parentInfo = el.p" +
"arent().parent();\r\n            updateItemInfo(parentInfo);\r\n        });\r\n\r\n     " +
"   discountInput.on(\"blur\", function () {\r\n            const el = $(this);\r\n    " +
"        const value = el.val();\r\n\r\n            if (!value) {\r\n                re" +
"turn;\r\n            };\r\n\r\n            if (value.substr(value.length - 1) === \"%\")" +
" {\r\n                return;\r\n            };\r\n\r\n            el.val(el.val() + \"%\"" +
");\r\n            const parentInfo = el.parent().parent();\r\n            updateItem" +
"Info(parentInfo);\r\n        });\r\n\r\n        function getPrice(el) {\r\n            f" +
"unction request(itemId, customerId, priceTypeId, unitId) {\r\n                var " +
"url = \"/dashboard/sales/tasks/selling-price/{itemId}/{customerId}/{priceTypeId}/" +
"{unitId}\";\r\n                url = url.replace(\"{itemId}\", itemId);\r\n            " +
"    url = url.replace(\"{customerId}\", customerId);\r\n                url = url.re" +
"place(\"{priceTypeId}\", priceTypeId);\r\n                url = url.replace(\"{unitId" +
"}\", unitId);\r\n\r\n                return window.getAjaxRequest(url);\r\n            " +
"};\r\n\r\n            const itemId = el.attr(\"data-item-id\");\r\n            const cus" +
"tomerId = parseInt($(\"#CustomerInputText\").attr(\"data-customer-id\")) || 0;\r\n    " +
"        const priceTypeId = parseInt($(\"#PriceTypeSelect\").val()) || 0;\r\n       " +
"     const unitId = el.val();\r\n\r\n            $(\".action.panel.segment\").addClass" +
"(\"loading\");\r\n            const ajax = request(itemId, customerId, priceTypeId, " +
"unitId);\r\n\r\n            ajax.success(function (response) {\r\n                $(\"." +
"action.panel.segment\").removeClass(\"loading\");\r\n                const priceInput" +
" = el.parent().parent().parent().find(\"input.price\");\r\n                priceInpu" +
"t.val(response).trigger(\"keyup\");\r\n            });\r\n\r\n            ajax.fail(func" +
"tion (xhr) {\r\n                $(\".action.panel.segment\").removeClass(\"loading\");" +
"\r\n                console.log(window.getAjaxErrorMessage(xhr));\r\n            });" +
"\r\n        };\r\n\r\n        unitSelect.on(\"change\", function () {\r\n            getPr" +
"ice($(this));\r\n        });\r\n\r\n        item.on(\"contextmenu\", function (e) {\r\n   " +
"         e.preventDefault();\r\n            const el = $(this);\r\n            const" +
" inputEl = el.find(\".number.block input\");\r\n            const buttonEl = el.find" +
"(\".number.block button\");\r\n\r\n            inputEl.toggle();\r\n            buttonEl" +
".toggle();\r\n        });\r\n\r\n        item.appendTo(targetEl);\r\n        quantityInp" +
"ut.trigger(\"keyup\");\r\n        window.setNumberFormat();\r\n        window.updateTo" +
"tal();\r\n\r\n        var tabId = window.getSelectedTabId();\r\n        var triggerNam" +
"e = \"itemAdded\";\r\n\r\n        $(document).trigger(triggerName, [tabId, itemId]);\r\n" +
"\r\n        if (typeof (callback) === \"function\") {\r\n            callback(el);\r\n  " +
"      };\r\n    };\r\n\r\n    function initializeClickAndAction() {\r\n        $(\"#POSIt" +
"emList .item\").unbind(\"click\").bind(\"click\", function () {\r\n            const el" +
" = $(this);\r\n\r\n            defaulPOSItemClick(el);\r\n        });\r\n    };\r\n\r\n    f" +
"unction fetchUnits() {\r\n        function request() {\r\n            const url = \"/" +
"api/forms/inventory/units/all\";\r\n            return window.getAjaxRequest(url);\r" +
"\n        };\r\n\r\n        const ajax = request();\r\n\r\n        ajax.success(function " +
"(response) {\r\n            window.metaUnits = response;\r\n        });\r\n    };\r\n\r\n " +
"   function fetchProducts() {\r\n        function request() {\r\n            const u" +
"rl = \"/dashboard/sales/tasks/items\";\r\n            return window.getAjaxRequest(u" +
"rl);\r\n        };\r\n\r\n        const ajax = request();\r\n\r\n        ajax.success(func" +
"tion (response) {\r\n            window.products = response;\r\n            $(docume" +
"nt).trigger(\"itemFetched\");\r\n        });\r\n    };\r\n\r\n    $(\".search.panel input\")" +
".keyup(function () {\r\n        const el = $(this);\r\n        const term = el.val()" +
";\r\n\r\n        const categoryEl = $(\".category.list .selected.category\");\r\n       " +
" var category = \"\";\r\n\r\n        if (categoryEl.length) {\r\n            category = " +
"categoryEl.text();\r\n        };\r\n\r\n        window.displayProducts(category, term)" +
";\r\n\r\n        initializeClickAndAction();\r\n    });\r\n\r\n    $(\".search.panel input\"" +
").keydown(function (e) {\r\n        if (e.keyCode === 13) {\r\n            const ite" +
"m = $(\".item.list .item:first\");\r\n\r\n            if (item.length) {\r\n            " +
"    item.trigger(\"click\");\r\n            };\r\n        };\r\n    });\r\n\r\n    window.fe" +
"tchUnits();\r\n    window.fetchProducts();\r\n\r\n    $(document).on(\"itemFetched\", fu" +
"nction () {\r\n        $(\"#POSDimmer\").removeClass(\"active\");\r\n        displayProd" +
"ucts();\r\n        displayCategories();\r\n        initializeClickAndAction();\r\n    " +
"});\r\n\r\n    function displayCategories() {\r\n        const categories = window.Enu" +
"merable.From(products).Distinct(function (x) { return x.ItemGroupName }).Select(" +
"function (x) { return x.ItemGroupName }).ToArray();\r\n        var targetEl = $(\"." +
"cat.filter\");\r\n        $(\".category.list\").find(\".category\").remove();\r\n\r\n      " +
"  targetEl.unbind(\"click\").bind(\"click\", function () {\r\n            displayProdu" +
"cts();\r\n            $(\".category\").removeClass(\"selected\");\r\n            targetE" +
"l.hide();\r\n            initializeClickAndAction();\r\n        });\r\n\r\n        $.eac" +
"h(categories, function () {\r\n            const category = $(\"<div class=\'categor" +
"y\' />\");\r\n            category.html(this);\r\n\r\n            category.unbind(\"click" +
"\").bind(\"click\", function () {\r\n                $(\".search.panel input\").val(\"\")" +
";\r\n                const el = $(this);\r\n                const name = el.text();\r" +
"\n\r\n                if (name) {\r\n                    displayProducts(name);\r\n    " +
"                $(\".category\").removeClass(\"selected\");\r\n                    el." +
"addClass(\"selected\");\r\n\r\n                    targetEl.show();\r\n                }" +
" else {\r\n                    targetEl.hide();\r\n                };\r\n\r\n           " +
"     initializeClickAndAction();\r\n            });\r\n\r\n            targetEl.before" +
"(category);\r\n        });\r\n    };\r\n\r\n    function displayProducts(category, searc" +
"hQuery) {\r\n        var target = $(\"#POSItemList\");\r\n\r\n        var groupItems;\r\n\r" +
"\n        if (!category && !searchQuery) {\r\n            groupItems = products;\r\n " +
"       } else {\r\n            if (category && searchQuery) {\r\n                gro" +
"upItems = window.Enumerable\r\n                    .From(products)\r\n              " +
"      .Where(function (x) {\r\n                        return x.ItemGroupName.toLo" +
"werCase() === category.toString().toLowerCase()\r\n                            && " +
"x.ItemName.toLowerCase().indexOf(searchQuery.toLowerCase()) > -1;\r\n             " +
"       }).ToArray();\r\n            } else if (!category && searchQuery) {\r\n      " +
"          groupItems = window.Enumerable\r\n                    .From(products)\r\n " +
"                   .Where(function (x) {\r\n                        return x.ItemN" +
"ame.toLowerCase().indexOf(searchQuery.toLowerCase()) > -1;\r\n                    " +
"}).ToArray();\r\n            } else {\r\n                groupItems = window.Enumera" +
"ble\r\n                    .From(products)\r\n                    .Where(function (x" +
") {\r\n                        return x.ItemGroupName.toLowerCase() === category.t" +
"oString().toLowerCase();\r\n                    }).ToArray();\r\n            };\r\n   " +
"     };\r\n\r\n\r\n        target.html(\"\").hide();\r\n\r\n        groupItems = window.Enum" +
"erable.From(groupItems).OrderBy(function (x) { return x.ItemId; }).ToArray();\r\n\r" +
"\n        $.each(groupItems, function () {\r\n            const product = this;\r\n\r\n" +
"            const item = $(\"<div class=\'item\' />\");\r\n            item.attr(\"data" +
"-item-id\", product.ItemId);\r\n            item.attr(\"data-item-code\", product.Ite" +
"mCode);\r\n            item.attr(\"data-item-name\", product.ItemName);\r\n           " +
" item.attr(\"data-item-group\", product.ItemGroupName);\r\n            item.attr(\"da" +
"ta-brand\", product.BrandName);\r\n            item.attr(\"data-unit-id\", product.Un" +
"itId);\r\n            item.attr(\"data-valid-units\", product.ValidUnits);\r\n        " +
"    item.attr(\"data-barcode\", product.Barcode);\r\n            item.attr(\"data-pho" +
"to\", product.Photo);\r\n            item.attr(\"data-is-taxable-item\", product.IsTa" +
"xableItem);\r\n            item.attr(\"data-selling-price\", product.SellingPrice);\r" +
"\n\r\n            if (product.HotItem) {\r\n                item.addClass(\"hot\");\r\n  " +
"          };\r\n\r\n            const info = $(\"<div class=\'info\' />\");\r\n\r\n         " +
"   const price = $(\"<div class=\'price\' />\");\r\n            price.html(product.Sel" +
"lingPrice);\r\n\r\n            price.appendTo(info);\r\n\r\n\r\n            const photo = " +
"$(\"<div class=\'photo\' />\");\r\n\r\n            if (product.Photo) {\r\n               " +
" const img = $(\"<img />\");\r\n                img.attr(\"src\", product.Photo + \"?He" +
"ight=200&Width=200\");\r\n\r\n                img.appendTo(photo);\r\n            };\r\n\r" +
"\n            photo.appendTo(info);\r\n\r\n            const name = $(\"<div class=\'na" +
"me\' />\");\r\n            name.html(product.ItemName);\r\n\r\n            name.appendTo" +
"(info);\r\n\r\n            info.appendTo(item);\r\n            item.appendTo(target);\r" +
"\n        });\r\n\r\n        if (searchQuery) {\r\n            target.show();\r\n        " +
"    return;\r\n        };\r\n\r\n        target.fadeIn(500);\r\n    };\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
