#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/POSItemList.cshtml")]
    public partial class _Views_Shared_POSItemList_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_POSItemList_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"category list\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"cat filter\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        Clear\r\n        <i");

WriteLiteral(" class=\"delete icon\"");

WriteLiteral("></i>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"search panel\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"search\"");

WriteLiteral(" placeholder=\"Search ...\"");

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"item list\"");

WriteLiteral(" id=\"POSItemList\"");

WriteLiteral(">\r\n</div>\r\n<script>\r\n    var itemTemplate = `<div class=\"item\" id=\"pos-{ItemId}\" " +
"data-selling-price=\"{SellingPrice}\" data-photo=\"{Photo}\" data-unit-id=\"{UnitId}\"" +
" data-valid-units=\"{ValidUnits}\" data-brand=\"{BrandName}\" data-item-group=\"{Item" +
"GroupName}\" data-item-name=\"{ItemName}\" data-item-code=\"{ItemCode}\" data-item-id" +
"=\"{ItemId}\" data-price=\"{Price}\">\r\n\t<div class=\"photo block\">\r\n\t\t<img src=\"{Phot" +
"o}\">\r\n\t</div>\r\n\t<div class=\"info block\">\r\n\t\t<div class=\"header\">{ItemName}</div>" +
"\r\n\t\t<div class=\"price info\">\r\n\t\t\t<span class =\"rate\">{SellingPrice}</span>\r\n\t\t\t<" +
"span>&nbsp; x&nbsp; </span>\r\n\t\t\t<span class=\"quantity\">1</span>\r\n\t\t\t<span>&nbsp;" +
" =&nbsp; </span>\r\n\t\t\t<span class=\"amount\"></span>\r\n\t\t</div>\r\n\t\t<div class=\"disco" +
"unt info\" style=\"display:none;\">\r\n\t\t\t<span>Less&nbsp; </span>\r\n\t\t\t<span class=\"d" +
"iscount rate\"></span>\r\n\t\t\t<span>&nbsp; =&nbsp; </span>\r\n\t\t\t<span class=\"discount" +
"ed amount\"></span>\r\n\t\t</div>\r\n\t\t<div>\r\n\t\t\t<select class=\"unit inverted\" data-ite" +
"m-id=\"{ItemId}\">\r\n\t\t\t</select>\r\n\t\t</div>\r\n\t</div>\r\n\t<div class=\"number block\">\r\n" +
"\t\t<input type=\"text\" class =\"decimal price\" title=\"Edit Price\" value=\"{SellingPr" +
"ice}\">\r\n\t\t<input type=\"text\" class=\"decimal quantity\" title=\"Enter Quantity\" val" +
"ue=\"1\">\r\n\t\t<input type=\"text\" class=\"decimal discount\" title=\"Enter Rate of Disc" +
"ount\" value=\"\">\r\n\t\t<button class=\"ui red fluid button\" onclick=\"removeItem(this)" +
";\" style=\"display:none;\">Delete</button>\r\n\t</div>\r\n</div>`\r\n</script>\r\n\r\n<script" +
">\r\n    var products = [];\r\n    var metaUnits = [];\r\n\r\n    function defaulPOSItem" +
"Click(el, callback) {\r\n        var targetEl = $(\"#SalesItems\");\r\n\r\n        $(\".t" +
"ender.info.items\").hide();\r\n        $(\".footer.items\").show();\r\n        targetEl" +
".show();\r\n\r\n        var sellingPrice = el.attr(\"data-selling-price\");\r\n        v" +
"ar photo = el.attr(\"data-photo\");\r\n\r\n        var barCode = el.attr(\"data-barcode" +
"\");\r\n        var brand = el.attr(\"data-brand\");\r\n        var unitId = el.attr(\"d" +
"ata-unit-id\");\r\n        var validUnits = el.attr(\"data-valid-units\");\r\n        v" +
"ar itemGroup = el.attr(\"data-item-group\");\r\n        var itemName = el.attr(\"data" +
"-item-name\");\r\n        var itemCode = el.attr(\"data-item-code\");\r\n        var it" +
"emId = el.attr(\"data-item-id\");\r\n        var price = window.parseFloat2(sellingP" +
"rice || 0);\r\n\r\n        if (!price) {\r\n            window.displayMessage(\"Cannot " +
"add item because the price is zero.\");\r\n            return;\r\n        };\r\n\r\n\r\n\r\n " +
"       var selector = \"pos-\" + itemId;\r\n        var existingEl = $(\"#\" + selecto" +
"r);\r\n\r\n        if (existingEl.length) {\r\n            var existingQuantitySpan = " +
"existingEl.find(\"span.quantity\");\r\n            var existingQuantityInput = exist" +
"ingEl.find(\"input.quantity\");\r\n\r\n            var quantity = window.parseFloat2(e" +
"xistingQuantitySpan.text() || 0);\r\n            quantity++;\r\n\r\n            existi" +
"ngQuantitySpan.text(quantity);\r\n            existingQuantityInput.val(quantity)." +
"trigger(\"keyup\");\r\n\r\n            window.updateTotal();\r\n            return;\r\n   " +
"     };\r\n\r\n        var template = itemTemplate;\r\n\r\n        template = template.r" +
"eplace(/{ItemId}/g, itemId);\r\n        template = template.replace(/{SellingPrice" +
"}/g, sellingPrice);\r\n        template = template.replace(/{Photo}/g, photo);\r\n  " +
"      template = template.replace(/{BarCode}/g, barCode);\r\n        template = te" +
"mplate.replace(/{BrandName}/g, brand);\r\n        template = template.replace(/{It" +
"emGroupName}/g, itemGroup);\r\n        template = template.replace(/{ItemName}/g, " +
"itemName);\r\n        template = template.replace(/{ItemCode}/g, itemCode);\r\n     " +
"   template = template.replace(/{Price}/g, price);\r\n        template = template." +
"replace(/{UnitId}/g, unitId);\r\n        template = template.replace(/{ValidUnits}" +
"/g, validUnits);\r\n\r\n        var item = $(template);\r\n        var quantityInput =" +
" item.find(\"input.quantity\");\r\n        var priceInput = item.find(\"input.price\")" +
";\r\n        var discountInput = item.find(\"input.discount\");\r\n        var unitSel" +
"ect = item.find(\"select.unit\");\r\n\r\n        function loadUnits(el, defaultUnitId," +
" validUnits) {\r\n            el.html(\"\");\r\n\r\n            const units = window.Enu" +
"merable.From(window.metaUnits)\r\n                .Where(function (x) {\r\n         " +
"           return validUnits.indexOf(x.unit_id.toString()) > -1;\r\n              " +
"  }).ToArray();\r\n\r\n            $.each(units, function () {\r\n                cons" +
"t unit = this;\r\n\r\n                const option = $(\"<option/ >\");\r\n             " +
"   option.attr(\"value\", unit.unit_id);\r\n                option.html(unit.unit_na" +
"me);\r\n\r\n                if (defaultUnitId === unit.unit_id) {\r\n                 " +
"   option.attr(\"selected\", \"\");\r\n                };\r\n\r\n                option.ap" +
"pendTo(el);\r\n            });\r\n\r\n        };\r\n\r\n        loadUnits(unitSelect, unit" +
"Id, validUnits.split(\',\'));\r\n\r\n        function updateItemTotal(el) {\r\n         " +
"   const quantityEl = el.find(\"input.quantity\");\r\n            const discountEl =" +
" el.find(\"input.discount\");\r\n\r\n            const quantity = window.parseFloat2(q" +
"uantityEl.val() || 0);\r\n            const discountRate = window.parseFloat2(disc" +
"ountEl.val().replace(\"%\", \"\"));\r\n            const price = window.parseFloat2(el" +
".find(\"input.price\").val());\r\n\r\n            const amount = (price * quantity).to" +
"Fixed(2);\r\n            const discountedAmount = ((price * quantity) * ((100 - di" +
"scountRate) / 100)).toFixed(2);\r\n\r\n            el.find(\"span.rate:not(.discount)" +
"\").html(price);\r\n            el.find(\"span.quantity\").html(quantity);\r\n         " +
"   el.find(\"span.amount\").html(amount);\r\n            el.find(\"span.discount.rate" +
"\").html(\"\");\r\n            el.find(\"span.discounted.amount\").html(\"\");\r\n\r\n       " +
"     if (discountRate) {\r\n                el.find(\".discount.info\").show();\r\n   " +
"             el.find(\"span.discount.rate\").html(discountEl.val().replace(\"%\", \"\"" +
") + \"%\");\r\n                el.find(\"span.discounted.amount\").html(discountedAmou" +
"nt);\r\n            } else {\r\n                el.find(\".discount.info\").hide();\r\n " +
"           }\r\n\r\n            window.updateTotal();\r\n        };\r\n\r\n        quantit" +
"yInput.on(\"keyup\", function () {\r\n            const el = $(this);\r\n            c" +
"onst parentInfo = el.parent().parent();\r\n            updateItemTotal(parentInfo)" +
";\r\n        });\r\n\r\n        discountInput.on(\"keyup\", function () {\r\n            c" +
"onst el = $(this);\r\n\r\n            const rate = window.parseFloat2(el.val());\r\n  " +
"          if (rate > 100) {\r\n                el.val(\"100\");\r\n                ret" +
"urn;\r\n            };\r\n\r\n            const parentInfo = el.parent().parent();\r\n  " +
"          updateItemTotal(parentInfo);\r\n        });\r\n\r\n        priceInput.on(\"ke" +
"yup\", function () {\r\n            const el = $(this);\r\n            const parentIn" +
"fo = el.parent().parent();\r\n            updateItemTotal(parentInfo);\r\n        })" +
";\r\n\r\n        discountInput.on(\"blur\", function () {\r\n            const el = $(th" +
"is);\r\n            const value = el.val();\r\n\r\n            if (!value) {\r\n        " +
"        return;\r\n            };\r\n\r\n            if (value.substr(value.length - 1" +
") === \"%\") {\r\n                return;\r\n            };\r\n\r\n            el.val(el.v" +
"al() + \"%\");\r\n            const parentInfo = el.parent().parent();\r\n            " +
"updateItemTotal(parentInfo);\r\n        });\r\n\r\n        function getPrice(el) {\r\n  " +
"          function request(itemId, customerId, priceTypeId, unitId) {\r\n         " +
"       var url = \"/dashboard/sales/tasks/selling-price/{itemId}/{customerId}/{pr" +
"iceTypeId}/{unitId}\";\r\n                url = url.replace(\"{itemId}\", itemId);\r\n " +
"               url = url.replace(\"{customerId}\", customerId);\r\n                u" +
"rl = url.replace(\"{priceTypeId}\", priceTypeId);\r\n                url = url.repla" +
"ce(\"{unitId}\", unitId);\r\n\r\n                return window.getAjaxRequest(url);\r\n " +
"           };\r\n\r\n            const itemId = el.attr(\"data-item-id\");\r\n          " +
"  const customerId = parseInt($(\"#CustomerInputText\").attr(\"data-customer-id\")) " +
"|| 0;\r\n            const priceTypeId = parseInt($(\"#PriceTypeSelect\").val()) || " +
"0;\r\n            const unitId = el.val();\r\n\r\n            $(\".action.panel.segment" +
"\").addClass(\"loading\");\r\n            const ajax = request(itemId, customerId, pr" +
"iceTypeId, unitId);\r\n\r\n            ajax.success(function (response) {\r\n         " +
"       $(\".action.panel.segment\").removeClass(\"loading\");\r\n                const" +
" priceInput = el.parent().parent().parent().find(\"input.price\");\r\n              " +
"  priceInput.val(response).trigger(\"keyup\");\r\n            });\r\n\r\n            aja" +
"x.fail(function (xhr) {\r\n                $(\".action.panel.segment\").removeClass(" +
"\"loading\");\r\n                console.log(window.getAjaxErrorMessage(xhr));\r\n    " +
"        });\r\n        };\r\n\r\n        unitSelect.on(\"change\", function () {\r\n      " +
"      getPrice($(this));\r\n        });\r\n\r\n        item.on(\"contextmenu\", function" +
" (e) {\r\n            e.preventDefault();\r\n            const el = $(this);\r\n      " +
"      const inputEl = el.find(\".number.block input\");\r\n            const buttonE" +
"l = el.find(\".number.block button\");\r\n\r\n            inputEl.toggle();\r\n         " +
"   buttonEl.toggle();\r\n        });\r\n\r\n        item.appendTo(targetEl);\r\n        " +
"quantityInput.trigger(\"keyup\");\r\n        window.setNumberFormat();\r\n        wind" +
"ow.updateTotal();\r\n\r\n        var tabId = window.getSelectedTabId();\r\n        var" +
" triggerName = \"itemAdded\";\r\n\r\n        $(document).trigger(triggerName, [tabId, " +
"itemId]);\r\n\r\n        if (typeof (callback) === \"function\") {\r\n            callba" +
"ck(el);\r\n        };\r\n    };\r\n\r\n    function initializeClickAndAction() {\r\n      " +
"  $(\"#POSItemList .item\").unbind(\"click\").bind(\"click\", function () {\r\n         " +
"   const el = $(this);\r\n\r\n            defaulPOSItemClick(el);\r\n        });\r\n    " +
"};\r\n\r\n    function fetchUnits() {\r\n        function request() {\r\n            con" +
"st url = \"/api/forms/inventory/units/all\";\r\n            return window.getAjaxReq" +
"uest(url);\r\n        };\r\n\r\n        const ajax = request();\r\n\r\n        ajax.succes" +
"s(function (response) {\r\n            window.metaUnits = response;\r\n        });\r\n" +
"    };\r\n\r\n    function fetchProducts() {\r\n        function request() {\r\n        " +
"    const url = \"/dashboard/sales/tasks/items\";\r\n            return window.getAj" +
"axRequest(url);\r\n        };\r\n\r\n        const ajax = request();\r\n\r\n        ajax.s" +
"uccess(function (response) {\r\n            window.products = response;\r\n         " +
"   $(document).trigger(\"itemFetched\");\r\n        });\r\n    };\r\n\r\n    $(\".search.pa" +
"nel input\").keyup(function () {\r\n        const el = $(this);\r\n        const term" +
" = el.val();\r\n\r\n        const categoryEl = $(\".category.list .selected.category\"" +
");\r\n        var category = \"\";\r\n\r\n        if (categoryEl.length) {\r\n            " +
"category = categoryEl.text();\r\n        };\r\n\r\n        window.displayProducts(cate" +
"gory, term);\r\n\r\n        initializeClickAndAction();\r\n    });\r\n\r\n    $(\".search.p" +
"anel input\").keydown(function (e) {\r\n        if (e.keyCode === 13) {\r\n          " +
"  const item = $(\".item.list .item:first\");\r\n\r\n            if (item.length) {\r\n " +
"               item.trigger(\"click\");\r\n            };\r\n        };\r\n    });\r\n\r\n  " +
"  window.fetchUnits();\r\n    window.fetchProducts();\r\n\r\n    $(document).on(\"itemF" +
"etched\", function () {\r\n        $(\"#POSDimmer\").removeClass(\"active\");\r\n        " +
"displayProducts();\r\n        displayCategories();\r\n        initializeClickAndActi" +
"on();\r\n    });\r\n\r\n    function displayCategories() {\r\n        const categories =" +
" window.Enumerable.From(products).Distinct(function (x) { return x.ItemGroupName" +
" }).Select(function (x) { return x.ItemGroupName }).ToArray();\r\n        var targ" +
"etEl = $(\".cat.filter\");\r\n        $(\".category.list\").find(\".category\").remove()" +
";\r\n\r\n        targetEl.unbind(\"click\").bind(\"click\", function () {\r\n            d" +
"isplayProducts();\r\n            $(\".category\").removeClass(\"selected\");\r\n        " +
"    targetEl.hide();\r\n            initializeClickAndAction();\r\n        });\r\n\r\n  " +
"      $.each(categories, function () {\r\n            const category = $(\"<div cla" +
"ss=\'category\' />\");\r\n            category.html(this);\r\n\r\n            category.un" +
"bind(\"click\").bind(\"click\", function () {\r\n                $(\".search.panel inpu" +
"t\").val(\"\");\r\n                const el = $(this);\r\n                const name = " +
"el.text();\r\n\r\n                if (name) {\r\n                    displayProducts(n" +
"ame);\r\n                    $(\".category\").removeClass(\"selected\");\r\n            " +
"        el.addClass(\"selected\");\r\n\r\n                    targetEl.show();\r\n      " +
"          } else {\r\n                    targetEl.hide();\r\n                };\r\n\r\n" +
"                initializeClickAndAction();\r\n            });\r\n\r\n            targ" +
"etEl.before(category);\r\n        });\r\n    };\r\n\r\n    function displayProducts(cate" +
"gory, searchQuery) {\r\n        var target = $(\"#POSItemList\");\r\n\r\n        var gro" +
"upItems;\r\n\r\n        if (!category && !searchQuery) {\r\n            groupItems = p" +
"roducts;\r\n        } else {\r\n            if (category && searchQuery) {\r\n        " +
"        groupItems = window.Enumerable\r\n                    .From(products)\r\n   " +
"                 .Where(function (x) {\r\n                        return x.ItemGro" +
"upName.toLowerCase() === category.toString().toLowerCase()\r\n                    " +
"        && x.ItemName.toLowerCase().indexOf(searchQuery.toLowerCase()) > -1;\r\n  " +
"                  }).ToArray();\r\n            } else if (!category && searchQuery" +
") {\r\n                groupItems = window.Enumerable\r\n                    .From(p" +
"roducts)\r\n                    .Where(function (x) {\r\n                        ret" +
"urn x.ItemName.toLowerCase().indexOf(searchQuery.toLowerCase()) > -1;\r\n         " +
"           }).ToArray();\r\n            } else {\r\n                groupItems = win" +
"dow.Enumerable\r\n                    .From(products)\r\n                    .Where(" +
"function (x) {\r\n                        return x.ItemGroupName.toLowerCase() ===" +
" category.toString().toLowerCase();\r\n                    }).ToArray();\r\n        " +
"    };\r\n        };\r\n\r\n\r\n        target.html(\"\").hide();\r\n\r\n        groupItems = " +
"window.Enumerable.From(groupItems).OrderBy(function (x) { return x.ItemId; }).To" +
"Array();\r\n\r\n        $.each(groupItems, function () {\r\n            const product " +
"= this;\r\n\r\n            const item = $(\"<div class=\'item\' />\");\r\n            item" +
".attr(\"data-item-id\", product.ItemId);\r\n            item.attr(\"data-item-code\", " +
"product.ItemCode);\r\n            item.attr(\"data-item-name\", product.ItemName);\r\n" +
"            item.attr(\"data-item-group\", product.ItemGroupName);\r\n            it" +
"em.attr(\"data-brand\", product.BrandName);\r\n            item.attr(\"data-unit-id\"," +
" product.UnitId);\r\n            item.attr(\"data-valid-units\", product.ValidUnits)" +
";\r\n            item.attr(\"data-barcode\", product.Barcode);\r\n            item.att" +
"r(\"data-photo\", product.Photo);\r\n            item.attr(\"data-selling-price\", pro" +
"duct.SellingPrice);\r\n\r\n            if (product.HotItem) {\r\n                item." +
"addClass(\"hot\");\r\n            };\r\n\r\n            const info = $(\"<div class=\'info" +
"\' />\");\r\n\r\n            const price = $(\"<div class=\'price\' />\");\r\n            pr" +
"ice.html(product.SellingPrice);\r\n\r\n            price.appendTo(info);\r\n\r\n\r\n      " +
"      const photo = $(\"<div class=\'photo\' />\");\r\n\r\n            if (product.Photo" +
") {\r\n                const img = $(\"<img />\");\r\n                img.attr(\"src\", " +
"product.Photo + \"?Height=200&Width=200\");\r\n\r\n                img.appendTo(photo)" +
";\r\n            };\r\n\r\n            photo.appendTo(info);\r\n\r\n            const name" +
" = $(\"<div class=\'name\' />\");\r\n            name.html(product.ItemName);\r\n\r\n     " +
"       name.appendTo(info);\r\n\r\n            info.appendTo(item);\r\n            ite" +
"m.appendTo(target);\r\n        });\r\n\r\n        if (searchQuery) {\r\n            targ" +
"et.show();\r\n            return;\r\n        };\r\n\r\n        target.fadeIn(500);\r\n    " +
"};\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
