#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\POSScreen.cshtml"
    using Frapid.ApplicationState.Cache;
    
    #line default
    #line hidden
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    #line 2 "..\..\Views\Shared\POSScreen.cshtml"
    using MixERP.Sales.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/POSScreen.cshtml")]
    public partial class _Views_Shared_POSScreen_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_POSScreen_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\POSScreen.cshtml"
  
    var meta = AppUsers.GetCurrent();

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    html, body {\r\n        font-smooth: always;\r\n    }\r\n\r\n    ");

WriteLiteral("@media screen and (min-width: 1200px) {\r\n        #pos-container {\r\n            fo" +
"nt-size: 9px !important;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@media screen and (min-width: 1300px) {\r\n        #pos-container {\r\n            fo" +
"nt-size: 10px !important;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@media screen and (min-width: 1400px) {\r\n        #pos-container {\r\n            fo" +
"nt-size: 11px !important;\r\n        }\r\n    }\r\n\r\n    .sales.layout, #pos-container" +
" {\r\n        height: 100%;\r\n    }\r\n\r\n        #pos-container .dimmer {\r\n          " +
"  font-weight: lighter;\r\n            letter-spacing: 1px;\r\n            font-size" +
": 1.5em;\r\n            text-transform: uppercase;\r\n            position: relative" +
";\r\n            top: 50%;\r\n            -webkit-transform: translateY(-50%);\r\n    " +
"        -ms-transform: translateY(-50%);\r\n            transform: translateY(-50%" +
");\r\n            text-align: center;\r\n        }\r\n\r\n            #pos-container .di" +
"mmer div.spinner {\r\n                padding: 0.5em;\r\n            }\r\n\r\n    #dashb" +
"oard-container {\r\n        padding: 0 !important;\r\n    }\r\n\r\n    #TenderInputText," +
" #ChangeInputText {\r\n        color: yellow !important;\r\n        font-size: 1.5em" +
";\r\n    }\r\n\r\n    #GiftCardNumberBalanceInputText {\r\n        color: yellow !import" +
"ant;\r\n    }\r\n\r\n    #TicketIframe {\r\n        background-color: white;\r\n        wi" +
"dth: 100%;\r\n        height: 600px;\r\n        border: none;\r\n        margin: 1em 0" +
".2em;\r\n        padding: 0.5em;\r\n        box-shadow: 2px 2px 10px #ddd;\r\n    }\r\n\r" +
"\n    .ticket.panel {\r\n        display: none;\r\n    }\r\n\r\n    .customer.search.moda" +
"l {\r\n        height: 100%;\r\n    }\r\n\r\n\r\n        .customer.search.modal iframe {\r\n" +
"            border: none;\r\n            background-color: white;\r\n            wid" +
"th: 100%;\r\n            height: 1000px;\r\n            display: block;\r\n        }\r\n" +
"\r\n    .inverted.header, .inverted.form {\r\n        background: transparent !impor" +
"tant;\r\n    }\r\n\r\n    input.invoice.number.for.reprint {\r\n        background: tran" +
"sparent !important;\r\n        border: 1px solid #555 !important;\r\n        color: " +
"#eee !important;\r\n    }\r\n\r\n    .inverted.info.message {\r\n        background-colo" +
"r: #B3A12E !important;\r\n        border: 1px solid #B3A12E !important;\r\n        c" +
"olor: #fff !important;\r\n    }\r\n\r\n    .info {\r\n        padding: 0.25em 0.5em;\r\n  " +
"      display: inline-block;\r\n        margin: 1px;\r\n        -ms-border-radius: 4" +
"px;\r\n        border-radius: 4px;\r\n        font-weight: bold;\r\n        text-trans" +
"form: uppercase;\r\n        font-size: 0.92em;\r\n    }\r\n\r\n    .office.info {\r\n     " +
"   background-color: #D65302;\r\n    }\r\n\r\n    .user.info {\r\n        background-col" +
"or: #68A800;\r\n    }\r\n\r\n    .area.info {\r\n        background-color: #02B3D6;\r\n   " +
" }\r\n\r\n    .counter.info {\r\n        background-color: #AC02D6;\r\n    }\r\n\r\n\r\n\r\n    " +
".status.head {\r\n        background-color: #444;\r\n        padding: 1em;\r\n        " +
"cursor: pointer;\r\n    }\r\n\r\n    .inline.blocks > .item {\r\n        display: inline" +
"-block !important;\r\n        padding: 2px;\r\n        width: 200px;\r\n    }\r\n\r\n    ." +
"two.inline.blocks > .item {\r\n        width: 50% !important;\r\n    }\r\n\r\n    .three" +
".inline.blocks > .item {\r\n        width: 33% !important;\r\n    }\r\n\r\n    .four.inl" +
"ine.blocks > .item {\r\n        width: 25% !important;\r\n    }\r\n\r\n    .status.head " +
".left {\r\n        display: inline-block;\r\n        width: 40%;\r\n    }\r\n\r\n    .stat" +
"us.head .right {\r\n        display: inline-block;\r\n        text-align: right;\r\n  " +
"      width: 60%;\r\n    }\r\n\r\n    .item.list {\r\n        background-color: #333;\r\n " +
"       cursor: pointer;\r\n        text-align: center;\r\n    }\r\n\r\n        .item.lis" +
"t .item {\r\n            display: inline-flex;\r\n            background: linear-gra" +
"dient(to top, #222, #575553);\r\n            margin: 4px;\r\n            height: 280" +
"px;\r\n            padding: 0.5em;\r\n            width: 200px;\r\n            cursor:" +
" pointer;\r\n        }\r\n\r\n            .item.list .item:hover {\r\n                ba" +
"ckground: linear-gradient(to top, #575553, #222);\r\n            }\r\n\r\n            " +
".item.list .item .info {\r\n                overflow: hidden;\r\n            }\r\n\r\n  " +
"          .item.list .item .photo {\r\n                position: relative;\r\n      " +
"          top: -16px;\r\n                left: -2px;\r\n                width: 200px" +
";\r\n                height: 280px;\r\n            }\r\n\r\n\r\n            .item.list .it" +
"em:hover img {\r\n                filter: grayscale(0%) !important;\r\n             " +
"   transition: opacity 1s ease-in-out;\r\n            }\r\n\r\n\r\n            .item.lis" +
"t .item .info .photo img {\r\n                height: 300px;\r\n                filt" +
"er: grayscale(50%);\r\n            }\r\n\r\n            .item.list .item .info .name {" +
"\r\n                font-size: 1.4em;\r\n                font-weight: 100;\r\n        " +
"        position: relative;\r\n                z-index: 1;\r\n                top: -" +
"6.5em;\r\n                line-height: 1.2em;\r\n                text-align: center;" +
"\r\n                text-shadow: 2px 2px 5px black;\r\n            }\r\n\r\n            " +
".item.list .item .info .price {\r\n                font-size: 3em;\r\n              " +
"  font-weight: 100 !important;\r\n                text-align: right;\r\n            " +
"    position: relative;\r\n                z-index: 1;\r\n                top: 0.7em" +
";\r\n                text-shadow: -2px 3px 10px #000;\r\n                color: #eee" +
";\r\n            }\r\n\r\n\r\n    .category.list {\r\n        padding: 4px;\r\n        text-" +
"align: center;\r\n        background-color: #555;\r\n    }\r\n\r\n        .category.list" +
" .filter {\r\n            text-align: right;\r\n            display: inline-block;\r\n" +
"        }\r\n\r\n        .category.list .category, .cat.filter {\r\n            displa" +
"y: inline-block;\r\n            background-color: #555;\r\n            color: white;" +
"\r\n            padding: 4px 12px;\r\n            margin: 2px;\r\n            border-r" +
"adius: 12px;\r\n            text-transform: uppercase;\r\n            font-size: 0.9" +
"em;\r\n            letter-spacing: 1px;\r\n            cursor: pointer;\r\n           " +
" text-shadow: 0 0 2px white;\r\n        }\r\n\r\n        .category.list .cat.filter {\r" +
"\n            background-color: #444;\r\n        }\r\n\r\n        .category.list .categ" +
"ory.selected, .category.list .category:hover {\r\n            background-color: #7" +
"8AD05;\r\n        }\r\n\r\n        .category.list .cat.filter:hover {\r\n            bac" +
"kground-color: #FA6400 !important;\r\n        }\r\n\r\n    .search.panel {\r\n        ba" +
"ckground-color: #666;\r\n        padding: 1em;\r\n        text-align: center;\r\n    }" +
"\r\n\r\n        .search.panel input {\r\n            text-align: center;\r\n            " +
"font-size: 1.1em;\r\n            background-color: transparent;\r\n            borde" +
"r: 1px solid #999;\r\n            border-radius: 2em;\r\n            text-transform:" +
" uppercase;\r\n            height: 2em;\r\n            width: 20em;\r\n        }\r\n\r\n\r\n" +
"    .sales.items .item {\r\n        background-color: #333;\r\n        padding: 3px " +
"9px;\r\n        border-bottom: 1px dotted #444;\r\n        cursor: pointer;\r\n       " +
" -webkit-user-select: none; /* webkit (safari, chrome) browsers */\r\n        -moz" +
"-user-select: none; /* mozilla browsers */\r\n        -khtml-user-select: none; /*" +
" webkit (konqueror) browsers */\r\n        -ms-user-select: none; /* IE10+ */\r\n   " +
" }\r\n\r\n        .sales.items .item:nth-child(even) {\r\n            background-color" +
": #373737 !important;\r\n        }\r\n\r\n        .sales.items .item:hover {\r\n        " +
"    background-color: #3a3a3a !important;\r\n        }\r\n\r\n        .sales.items .it" +
"em .block {\r\n            display: inline-block;\r\n            height: 112px;\r\n   " +
"         overflow: hidden;\r\n        }\r\n\r\n            .sales.items .item .block i" +
"mg {\r\n                height: 112px;\r\n            }\r\n\r\n        .sales.items .ite" +
"m .photo.block {\r\n            width: 90px;\r\n            overflow: hidden;\r\n     " +
"   }\r\n\r\n        .sales.items .item .number.block {\r\n            width: 120px;\r\n " +
"       }\r\n\r\n\r\n            .sales.items .item .number.block button {\r\n           " +
"     height: 100%;\r\n                text-transform: uppercase;\r\n                " +
"letter-spacing: 1px;\r\n                font-weight: 100;\r\n            }\r\n\r\n      " +
"  .sales.items .item input {\r\n            font-size: 1.3em;\r\n            margin:" +
" 0 0 0.3em 0;\r\n            background-color: #333;\r\n            border: 1px soli" +
"d #555;\r\n            width: 100%;\r\n            padding: 4px 16px;\r\n            t" +
"ext-align: right;\r\n            border-radius: 0.5em;\r\n        }\r\n\r\n        .sale" +
"s.items .item .info.block {\r\n            width: calc(100% - 220px);\r\n           " +
" padding: 1em;\r\n        }\r\n\r\n            .sales.items .item .info.block .price.i" +
"nfo,\r\n            .sales.items .item .info.block .discount.info,\r\n            .s" +
"ales.items .item .info.block .header {\r\n                display: block;\r\n       " +
"     }\r\n\r\n            .sales.items .item .info.block .header {\r\n                " +
"font-size: 1.5em;\r\n                font-weight: 100;\r\n                text-trans" +
"form: uppercase;\r\n            }\r\n\r\n            .sales.items .item .info.block .p" +
"rice.info {\r\n                padding-top: 4px;\r\n            }\r\n\r\n            .sa" +
"les.items .item .info.block .price.info,\r\n            .sales.items .item .info.b" +
"lock .discount.info {\r\n                font-size: 1.1em;\r\n                text-a" +
"lign: left;\r\n                padding: 0;\r\n                text-transform: none;\r" +
"\n                color: #fbd842;\r\n            }\r\n\r\n\r\n    .tender.info {\r\n       " +
" background-color: #333;\r\n        width: 100%;\r\n        cursor: pointer;\r\n      " +
"  margin: 0 0 8px 0;\r\n        padding: 6px 0;\r\n    }\r\n\r\n\r\n        .tender.info:h" +
"over {\r\n            background-color: #3f3f3f;\r\n        }\r\n\r\n\r\n    .summary.item" +
"s {\r\n        padding: 0.5em 1em;\r\n        display: flex;\r\n    }\r\n\r\n        .summ" +
"ary.items > .item {\r\n            display: inline-flex;\r\n            flex-directi" +
"on: column;\r\n            padding: 2px;\r\n        }\r\n\r\n    .three.summary.items > " +
".item {\r\n        width: 32%;\r\n    }\r\n\r\n    .two.summary.items > .item {\r\n       " +
" width: 48%;\r\n    }\r\n\r\n    .one.summary.items > .item {\r\n        width: 96%;\r\n  " +
"  }\r\n\r\n    .summary.items > .item > .description {\r\n        padding-bottom: 0.5e" +
"m;\r\n        font-size: 0.9em;\r\n        text-align: left;\r\n    }\r\n\r\n    .summary." +
"items > .item > .money {\r\n        padding-top: 0.1em;\r\n        font-size: 3em;\r\n" +
"    }\r\n\r\n\r\n    input.pan.number,\r\n    input.customer.name,\r\n    input.customer.a" +
"ddress {\r\n        font-size: 12px !important;\r\n        padding: 8px !important;\r" +
"\n    }\r\n\r\n    .customer.name.item {\r\n        width: 40% !important;\r\n    }\r\n\r\n  " +
"  .customer.address.item {\r\n        width: 30% !important;\r\n    }\r\n\r\n    .pan.nu" +
"mber.item {\r\n        width: 25% !important;\r\n    }\r\n\r\n    .inverted.dropdown,\r\n " +
"   .inverted.dropdown input.search,\r\n    .inverted.dropdown .menu,\r\n    .inverte" +
"d.dropdown .item,\r\n    .inverted.dropdown .message {\r\n        background-color: " +
"#555 !important;\r\n        color: #eee !important;\r\n        border: 1px solid #66" +
"6 !important;\r\n    }\r\n\r\n        .inverted.dropdown .item.selected,\r\n        .inv" +
"erted.dropdown .item:hover {\r\n            background-color: #666 !important;\r\n  " +
"      }\r\n\r\n    .summary.items input,\r\n    .summary.items select,\r\n    .inverted." +
"input,\r\n    .inverted.select {\r\n        background-color: #555 !important;\r\n    " +
"    color: #eee !important;\r\n        border: 1px solid #666 !important;\r\n       " +
" padding: .87em;\r\n        border-radius: 0.4em;\r\n        width: 100%;\r\n        -" +
"moz-appearance: none; /* Firefox */\r\n    }\r\n\r\n    .summary.items .dropdown {\r\n  " +
"      padding: 1em !important;\r\n    }\r\n\r\n    select.inverted {\r\n        backgrou" +
"nd-color: #333;\r\n        border: 1px solid #555;\r\n        width: 100%;\r\n        " +
"padding: 0.55em 1em;\r\n        border-radius: 0.5em;\r\n        -moz-appearance: no" +
"ne; /* Firefox */\r\n    }\r\n\r\n    #dashboard-container {\r\n        padding: 0 !impo" +
"rtant;\r\n    }\r\n\r\n    #pos-container {\r\n        background-color: #555;\r\n    }\r\n\r" +
"\n\r\n    .pos.tabs {\r\n        display: flex;\r\n        padding: 0;\r\n    }\r\n\r\n\r\n    " +
"    .pos.tabs .item {\r\n            display: inline-flex;\r\n            flex-direc" +
"tion: column;\r\n            background: #444;\r\n            margin: 0 0.5em 0 0;\r\n" +
"            font-weight: bold;\r\n            font-size: 1.3em;\r\n            paddi" +
"ng: 0.75em 1em;\r\n            border-radius: 0.5em 0.5em 0 0;\r\n            cursor" +
": pointer;\r\n            text-shadow: 2px 2px 20px #222;\r\n        }\r\n\r\n          " +
"  .pos.tabs .selected.item,\r\n            .pos.tabs .active.item,\r\n            .p" +
"os.tabs .item:hover {\r\n                background: #C6A13D;\r\n                col" +
"or: #eee;\r\n            }\r\n\r\n    .circular.button {\r\n        padding: 0.9em 2em !" +
"important;\r\n    }\r\n\r\n    #pos-items {\r\n        background-color: #3a3a3a;\r\n     " +
"   height: 100%;\r\n        padding: 1em;\r\n    }\r\n\r\n    .tabs .actions {\r\n        " +
"background: #555;\r\n        width: 100%;\r\n        text-align: right;\r\n        mar" +
"gin: 0 !important;\r\n    }\r\n\r\n        .tabs .actions .icon {\r\n            cursor:" +
" pointer;\r\n        }\r\n\r\n    .ui.action.panel.inverted.segment {\r\n        backgro" +
"und: none !important;\r\n    }\r\n\r\n    .action.panel .toolbar {\r\n        display: f" +
"lex;\r\n        background-color: #2f2f2f;\r\n        background: linear-gradient(to" +
" top, #222, #444);\r\n        text-align: right;\r\n    }\r\n\r\n        .action.panel ." +
"toolbar > .item {\r\n            text-align: center;\r\n            display: inline-" +
"flex;\r\n            flex-direction: column-reverse;\r\n            background: #3f3" +
"f3f;\r\n            background: linear-gradient(to top, #222, #444); /* Standard s" +
"yntax */\r\n            padding: 1em 0.6em;\r\n            border-right: 1px solid #" +
"333;\r\n            height: 3em;\r\n            width: 2.5em;\r\n            font-size" +
": 1.4em;\r\n            cursor: pointer;\r\n        }\r\n\r\n\r\n            .action.panel" +
" .toolbar > .item:hover {\r\n                background: #C4A03D;\r\n               " +
" background: linear-gradient(to bottom, #C4A03D, #C4343D); /* Standard syntax */" +
"\r\n            }\r\n\r\n    .summary.items > .item > .description {\r\n        text-tra" +
"nsform: uppercase;\r\n        font-weight: bold;\r\n    }\r\n\r\n    .header.items {\r\n  " +
"      background-color: #3f3f3f;\r\n        background: linear-gradient(to top, #2" +
"92929, #444); /* Standard syntax */\r\n        padding: 1em 1em 1.5em;\r\n    }\r\n\r\n\r" +
"\n\r\n        .header.items .count.item,\r\n        .header.items .count.item .descri" +
"ption {\r\n            text-align: right !important;\r\n        }\r\n\r\n            .he" +
"ader.items .count.item .money {\r\n                color: #FBD840;\r\n            }\r" +
"\n\r\n    .footer.items {\r\n        background-color: #3f3f3f;\r\n        background: " +
"linear-gradient(to top, #292929, #3a3a3a); /* Standard syntax */\r\n        paddin" +
"g: 1em;\r\n        text-align: right;\r\n    }\r\n\r\n    .action.panel.segment {\r\n     " +
"   padding: 0;\r\n        border: 0;\r\n        margin: 0;\r\n    }\r\n\r\n    .payment.ty" +
"pe.container {\r\n        padding-bottom: 1em;\r\n        border-bottom: 1px solid #" +
"444;\r\n    }\r\n\r\n    .show.anchor {\r\n        padding: 1em;\r\n        color: #C4A03D" +
";\r\n    }\r\n</style>\r\n<style>\r\n    /*Semantic UI Override*/\r\n    ");

WriteLiteral(@"@media only screen and (max-width: 500px) {
        .ui.buttons {
            display: block !important;
        }

            .ui.buttons .button {
                width: 100% !important;
                margin-bottom: 0.5em !important;
            }
    }
</style>
<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" id=\"pos-container\"");

WriteLiteral(" class=\"ui attached pos sales inverted segment\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"dimmer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"spinner\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"ui huge loading spinner icon\"");

WriteLiteral("></i>\r\n        </div>\r\n        <div>\r\n            We\'re loading things\r\n        <" +
"/div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"layout\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"pos tabs\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"new item\"");

WriteLiteral(">+</div>\r\n            <div");

WriteLiteral(" id=\"tab-item-1\"");

WriteLiteral(" class=\"selected item\"");

WriteLiteral(">\r\n                1\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"remove\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"delete icon\"");

WriteLiteral("></i>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"pos-items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui stackable grid\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"eleven wide column\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"status head\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"left\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"office info\"");

WriteLiteral(" title=\"Current Branch Office\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 665 "..\..\Views\Shared\POSScreen.cshtml"
                           Write(meta.OfficeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n                            <span");

WriteLiteral(" class=\"user info\"");

WriteLiteral(" title=\"You\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 668 "..\..\Views\Shared\POSScreen.cshtml"
                           Write(meta.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n                            <span");

WriteLiteral(" class=\"area info\"");

WriteLiteral(" title=\"Current Area\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 671 "..\..\Views\Shared\POSScreen.cshtml"
                           Write(meta.OfficeCode);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n                            <span");

WriteLiteral(" class=\"office info\"");

WriteLiteral(" title=\"Office Name\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 674 "..\..\Views\Shared\POSScreen.cshtml"
                           Write(meta.OfficeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n                        </div>\r\n\r\n        " +
"                <div");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"three inline blocks\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                                    <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"PriceTypeSelect\"");

WriteLiteral("></select>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                                    <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"StoreSelect\"");

WriteLiteral("></select>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                                    <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"CounterSelect\"");

WriteLiteral("></select>\r\n                                </div>\r\n                            <" +
"/div>\r\n                        </div>\r\n\r\n                    </div>\r\n\r\n");

WriteLiteral("                    ");

            
            #line 694 "..\..\Views\Shared\POSScreen.cshtml"
               Write(Html.PartialView("Shared/POSItemList.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"five wide column\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui action panel inverted segment\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"toggle view item\"");

WriteLiteral(" title=\"Toggle View\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"toggle off icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-payment-type=\"credit\"");

WriteLiteral(" title=\"Credit\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"tags icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-payment-type=\"cash\"");

WriteLiteral(" title=\"Cash\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"money icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-payment-type=\"check\"");

WriteLiteral(" title=\"Pay by Check\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"newspaper icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(" data-payment-type=\"gift-card\"");

WriteLiteral(" title=\"Pay by Gift Card\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"gift icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(" id=\"SearchCustomerAction\"");

WriteLiteral(" title=\"Search Customer\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"search icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"reprint ticket item\"");

WriteLiteral(" onclick=\"$(\'.reprint.ticket.modal\').modal(\'show\');\"");

WriteLiteral(" title=\"Reprint Ticket\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"print icon\"");

WriteLiteral("></i>\r\n                            </div>\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"action container\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 722 "..\..\Views\Shared\POSScreen.cshtml"
                       Write(Html.PartialView("Shared/SalesEntryForm.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                            <div");

WriteLiteral(" id=\"SalesItems\"");

WriteLiteral(" class=\"sales items\"");

WriteLiteral(">\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"footer items\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"ui clear negative circular button\"");

WriteLiteral(" id=\"ClearScreenButton\"");

WriteLiteral(">\r\n                                    Clear Screen\r\n                            " +
"    </div>\r\n                                <div");

WriteLiteral(" class=\"ui next positive circular button\"");

WriteLiteral(">Next</div>\r\n                            </div>\r\n                        </div>\r\n" +
"                    </div>\r\n                </div>\r\n            </div>\r\n        " +
"</div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n");

            
            #line 742 "..\..\Views\Shared\POSScreen.cshtml"
Write(Html.PartialView("Shared/CustomerSearchModal.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 743 "..\..\Views\Shared\POSScreen.cshtml"
Write(Html.PartialView("Shared/ReprintTicketModal.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 744 "..\..\Views\Shared\POSScreen.cshtml"
Write(Html.PartialView("Shared/GiftCardSerachModal.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var pageLoaded = false;\r\n\r\n    $(document).on(\"itemAdded\", func" +
"tion (e, tabId, itemId) {\r\n        const model = window.getModelById(tabId);\r\n  " +
"      if (!model) {\r\n            return;\r\n        };\r\n\r\n        const item = win" +
"dow.Enumerable.From(model.Details).Where(function (x) { return x.ItemId.toString" +
"() === itemId.toString(); }).FirstOrDefault();\r\n\r\n\r\n        if (!item) {\r\n      " +
"      return;\r\n        };\r\n\r\n        const el = $(\"#pos-\" + itemId);\r\n        co" +
"nst unitSelect = el.find(\"select.unit\");\r\n\r\n        if (unitSelect.length) {\r\n  " +
"          unitSelect.val(item.UnitId);\r\n        };\r\n\r\n        const quantityInpu" +
"t = el.find(\"input.quantity\");\r\n\r\n        if (quantityInput.length) {\r\n         " +
"   quantityInput.val(item.Quantity);\r\n        };\r\n\r\n        const priceInput = e" +
"l.find(\"input.price\");\r\n\r\n        if (priceInput.length) {\r\n            priceInp" +
"ut.val(item.Price);\r\n        };\r\n\r\n        const discountInput = el.find(\"input." +
"discount\");\r\n\r\n        if (discountInput.length) {\r\n            discountInput.va" +
"l(item.DiscountRate);\r\n        };\r\n\r\n        discountInput.trigger(\"keyup\");\r\n\r\n" +
"    });\r\n\r\n\r\n\r\n    $(\"#SalesItems .item\").on(\"contextmenu\", function (e) {\r\n    " +
"    e.preventDefault();\r\n        const el = $(this);\r\n        const defaultMenu " +
"= el.find(\".info.block, .number.block\");\r\n        const contextMenu = el.find(\"." +
"context.menu\");\r\n\r\n        defaultMenu.toggle();\r\n        contextMenu.toggle();\r" +
"\n    });\r\n</script>\r\n\r\n\r\n<script>\r\n\r\n    setTimeout(function () {\r\n        windo" +
"w.fetchProducts();\r\n    }, 120000);\r\n\r\n    function removeItem(el) {\r\n        co" +
"nst confirmed = confirm(\"Are you sure?\");\r\n\r\n        if (!confirmed) {\r\n        " +
"    return;\r\n        };\r\n\r\n        el = $(el);\r\n        const container = el.par" +
"ent().parent();\r\n        container.remove();\r\n        window.updateTotal();\r\n   " +
" };\r\n\r\n\r\n    $(\".toggle.view.item, .next.button\").unbind(\"click\").bind(\"click\", " +
"function () {\r\n        const salesItemState = $(\".sales.items\").is(\":visible\");\r" +
"\n\r\n        $(\".tender.info.items\").hide();\r\n        $(\".footer.items\").hide();\r\n" +
"        $(\".sales.items\").hide();\r\n\r\n        if(salesItemState) {\r\n            $" +
"(\".tender.info.items\").show();\r\n        }else {\r\n            $(\".footer.items\")." +
"show();\r\n            $(\".sales.items\").show();\r\n        };\r\n    });\r\n\r\n\r\n    $(\"" +
"#ReceiptSummary div.tender .money input\").keyup(function () {\r\n        window.up" +
"dateTotal();\r\n    });\r\n\r\n    $(\"#DiscountTypeSelect\").change(function () {\r\n    " +
"    window.updateTotal();\r\n    });\r\n\r\n    $(\"#DiscountInputText\").keyup(function" +
" () {\r\n        window.updateTotal();\r\n    });\r\n\r\n    function updateTotal() {\r\n " +
"       const candidates = $(\"#SalesItems div.item\");\r\n        const amountEl = $" +
"(\"div.amount .money\");\r\n        const countEl = $(\"div.count .money\");\r\n        " +
"const couponDiscountType = parseInt($(\"#DiscountTypeSelect\").val());\r\n        co" +
"nst couponDiscountRate = window.parseFloat2($(\"#DiscountInputText\").val());\r\n   " +
"     var discount;\r\n\r\n\r\n        var totalPrice = 0;\r\n        var totalQuantity =" +
" 0;\r\n\r\n        $.each(candidates, function () {\r\n            const el = $(this);" +
"\r\n            const quantityEl = el.find(\"input.quantity\");\r\n            const d" +
"iscountEl = el.find(\"input.discount\");\r\n\r\n            const quantity = window.pa" +
"rseFloat2(quantityEl.val() || 0);\r\n            const discountRate = window.parse" +
"Float2(discountEl.val().replace(\"%\", \"\"));\r\n            const price = window.par" +
"seFloat2(el.find(\"input.price\").val());\r\n\r\n            const amount = price * qu" +
"antity;\r\n            const discountedAmount = amount * ((100 - discountRate) / 1" +
"00);\r\n\r\n            totalPrice += (discountedAmount || amount);\r\n            tot" +
"alQuantity += quantity;\r\n        });\r\n\r\n        totalPrice = parseFloat(totalPri" +
"ce.toFixed(2));\r\n\r\n        if (couponDiscountType === 1 && couponDiscountRate > " +
"0 && couponDiscountRate <= 100) {\r\n            discount = totalPrice * (couponDi" +
"scountRate / 100);\r\n            totalPrice = totalPrice - discount;\r\n        } e" +
"lse if (couponDiscountType === 2 && couponDiscountRate > 0) {\r\n            //Dis" +
"count amount\r\n            totalPrice = totalPrice - couponDiscountRate;\r\n       " +
" };\r\n\r\n\r\n\r\n        amountEl.html(totalPrice.toFixed(2));\r\n        countEl.html(t" +
"otalQuantity.toFixed(2));\r\n    };\r\n\r\n\r\n\r\n</script>\r\n<script>\r\n    $(\"#ClearScree" +
"nButton\").unbind(\"click\").bind(\"click\", function () {\r\n        clearScreen();\r\n " +
"   });\r\n\r\n    function clearScreen() {\r\n        $(\"#SalesItems\").html(\"\");\r\n    " +
"    $(\"#CustomerInputText\").removeAttr(\"data-customer-id\").val(\"\");\r\n        $(\"" +
"#TenderInputText\").val(\"\");\r\n        $(\"#ChangeInputText\").val(\"\");\r\n\r\n        w" +
"indow.updateTotal();\r\n    };\r\n\r\n    function loadStores() {\r\n        window.disp" +
"layFieldBinder($(\"#StoreSelect\"), \"/api/forms/inventory/stores/display-fields\", " +
"true);\r\n    };\r\n\r\n    function loadPaymentTerms() {\r\n        window.displayField" +
"Binder($(\"#PaymentTermSelect\"), \"/api/forms/sales/payment-terms/display-fields\"," +
" false);\r\n    };\r\n\r\n    function loadShippers() {\r\n        window.displayFieldBi" +
"nder($(\"#ShipperSelect\"), \"/api/forms/inventory/shippers/display-fields\", true);" +
"\r\n    };\r\n\r\n    function loadCostCenters() {\r\n        window.displayFieldBinder(" +
"$(\"#CostCenterSelect\"), \"/api/forms/finance/cost-centers/display-fields\", true);" +
"\r\n    };\r\n\r\n    function loadPriceTypes() {\r\n        window.displayFieldBinder($" +
"(\"#PriceTypeSelect\"), \"/api/forms/sales/price-types/display-fields\", true);\r\n   " +
" };\r\n\r\n\r\n    loadStores();\r\n    loadPriceTypes();\r\n\r\n    loadCostCenters();\r\n   " +
" loadShippers();\r\n    loadPaymentTerms();\r\n\r\n    $(\'.ui.customer.search\').search" +
"({\r\n        apiSettings: {\r\n            url: \'/dashboard/sales/setup/customer/se" +
"arch/{query}\'\r\n        },\r\n        fields: {\r\n            results: \'Items\',\r\n   " +
"         title: \'CustomerCode\',\r\n            description: \'CustomerName\',\r\n     " +
"       image: \'Photo\',\r\n            price: \'PhoneNumbers\'\r\n        },\r\n        o" +
"nSelect: function (result) {\r\n            const customerId = result.CustomerId;\r" +
"\n            if (!customerId) {\r\n                return;\r\n            };\r\n\r\n    " +
"        $(\"#CustomerInputText\").attr(\"data-customer-id\", customerId);\r\n        }" +
",\r\n        minCharacters: 1\r\n    });\r\n\r\n    $(\"#StoreSelect\").change(function ()" +
" {\r\n        var el = $(this);\r\n\r\n        function loadCounters() {\r\n            " +
"const storeId = el.val();\r\n            const filters = [];\r\n            filters." +
"push(window.getAjaxColumnFilter(\"WHERE\", \"store_id\", \"int\", window.FilterConditi" +
"ons.IsEqualTo, storeId));\r\n\r\n            window.displayFieldBinder($(\"#CounterSe" +
"lect\"), \"/api/forms/inventory/counters/display-fields/get-where\", true, filters)" +
";\r\n        };\r\n\r\n        loadCounters();\r\n    });\r\n</script>\r\n\r\n<script>\r\n    fu" +
"nction initializeTabs() {\r\n        $(\".pos.tabs .item:not(.new)\").unbind(\"click\"" +
").bind(\"click\", function () {\r\n            window.saveState();\r\n            $(\"." +
"pos.tabs .item\").removeClass(\"selected\");\r\n            const el = $(this);\r\n    " +
"        el.addClass(\"selected\");\r\n            window.loadState();\r\n        });\r\n" +
"    };\r\n\r\n    $(\".tabs .new.item\").unbind(\"click\").bind(\"click\", function () {\r\n" +
"        var el = $(this);\r\n        window.saveState();\r\n\r\n        function creat" +
"eTab(id) {\r\n            const item = $(\"<div class=\'item\' />\");\r\n            ite" +
"m.attr(\"id\", \"tab-item-\" + id);\r\n            item.html(id);\r\n\r\n            el.si" +
"blings(\".actions\").before(item);\r\n        };\r\n\r\n        var items = [];\r\n       " +
" const candidates = $(\".tabs .item:not(.new)\");\r\n\r\n        $.each(candidates, fu" +
"nction () {\r\n            const el = $(this);\r\n            const id = parseInt(el" +
".text());\r\n            items.push(id);\r\n        });\r\n\r\n        const max = windo" +
"w.Enumerable.From(items).Max(function (x) { return x; });\r\n        var nextValue" +
" = 1;\r\n\r\n        if (max) {\r\n            nextValue = max + 1;\r\n        };\r\n\r\n   " +
"     createTab(nextValue);\r\n\r\n\r\n        initializeTabs();\r\n        $(\".tabs .ite" +
"m\").removeClass(\"selected\");\r\n        $(\"#tab-item-\" + nextValue).addClass(\"sele" +
"cted\");\r\n        clearScreen();\r\n    });\r\n\r\n    $(\".tabs .actions .delete.icon\")" +
".unbind(\"click\").bind(\"click\", function () {\r\n        const activeEl = $(\".tabs " +
".selected.item\");\r\n        const id = parseInt(activeEl.text());\r\n\r\n        if (" +
"activeEl.length && id > 1) {\r\n            const confirmed = window.confirm(\"Are " +
"you sure you want to delete this tab?\");\r\n\r\n            if (!confirmed) {\r\n     " +
"           return;\r\n            };\r\n\r\n            window.removeState();\r\n\r\n     " +
"       const previousEl = activeEl.prev(\".item\");\r\n            previousEl.addCla" +
"ss(\"selected\");\r\n            activeEl.remove();\r\n            window.loadState();" +
"\r\n        };\r\n    });\r\n\r\n    initializeTabs();\r\n\r\n    $(\".toolbar .item[data-pay" +
"ment-type]\").unbind(\"click\").bind(\"click\", function () {\r\n        const el = $(t" +
"his);\r\n        const paymentType = el.attr(\"data-payment-type\");\r\n        $(\".pa" +
"yment.type.container [data-payment-type]\").hide();\r\n        $(\".payment.type.con" +
"tainer [data-payment-type=\" + paymentType + \"]\").show();\r\n    });\r\n\r\n    $(\".sho" +
"w.more.anchor\").unbind(\"click\").bind(\"click\", function () {\r\n        const more " +
"= $(\".tender.info.items .more\");\r\n\r\n        more.show();\r\n        $(this).hide()" +
";\r\n    });\r\n\r\n    $(\".show.less.anchor\").unbind(\"click\").bind(\"click\", function " +
"() {\r\n        const more = $(\".tender.info.items .more\");\r\n\r\n        more.hide()" +
";\r\n        $(\".show.more.anchor\").show();\r\n    });\r\n\r\n    $(document).ajaxStop(f" +
"unction () {\r\n        if (!pageLoaded) {\r\n            $(\"#pos-container .dimmer\"" +
").hide();\r\n            $(\"#pos-container .layout\").fadeIn(500);\r\n        };\r\n\r\n " +
"       if (!pageLoaded) {\r\n            $(document).trigger(\"posready\");\r\n       " +
" };\r\n\r\n        pageLoaded = true;\r\n    });\r\n\r\n\r\n</script>\r\n\r\n<script>\r\n    setTi" +
"meout(function () {\r\n        $(\".decimal\").number(true, window.currencyDecimalPl" +
"aces, \".\", \"\");\r\n    }, 100);\r\n\r\n    //$(\"select:not(.ui)\").addClass(\"inverted f" +
"luid\").dropdown();\r\n\r\n    window.overridePath = \"/dashboard/sales/tasks/entry\";\r" +
"\n</script>\r\n<script>\r\n    $(\"#GiftCardNumberInputText\").on(\"change\", function ()" +
" {\r\n        function request(giftCardNumber) {\r\n            var url = \"/dashboar" +
"d/loyalty/tasks/gift-cards/get-balance/{giftCardNumber}\";\r\n            url = url" +
".replace(\"{giftCardNumber}\", giftCardNumber);\r\n\r\n            return window.getAj" +
"axRequest(url, \"POST\");\r\n        };\r\n\r\n        const el = $(this);\r\n        cons" +
"t giftCardNumber = el.val();\r\n\r\n        if (!giftCardNumber) {\r\n            retu" +
"rn;\r\n        };\r\n\r\n        const ajax = request(giftCardNumber);\r\n\r\n        ajax" +
".success(function (response) {\r\n            $(\"#GiftCardNumberBalanceInputText\")" +
".val(response);\r\n        });\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
