#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SalesEntryForm.cshtml")]
    public partial class _Views_Shared_SalesEntryForm_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_SalesEntryForm_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"header items\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"amount item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Amount</div>\r\n            <div");

WriteLiteral(" class=\"money\"");

WriteLiteral(">\r\n                <span></span>\r\n            </div>\r\n        </div>\r\n        <di" +
"v");

WriteLiteral(" class=\"count item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Count</div>\r\n            <div");

WriteLiteral(" class=\"money\"");

WriteLiteral(">\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"tender info items\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"payment type container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" data-payment-type=\"cash\"");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"tender item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Cash Tender</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" id=\"TenderInputText\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"change item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Cash Change</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" id=\"ChangeInputText\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" data-payment-type=\"credit\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" class=\"one summary items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"gift-card number item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Payment Term</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"PaymentTermSelect\"");

WriteLiteral("></select>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <" +
"div");

WriteLiteral(" data-payment-type=\"check\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"check amount item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Check Amount</div>\r\n                    <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CheckAmountInputText\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"check bank name item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Bank Name</div>\r\n                    <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BankNameInputText\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"        <div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"check number item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Check Number</div>\r\n                    <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CheckNumberInputText\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"check date item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Check Date</div>\r\n                    <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" id=\"CheckDateInputText\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n        <div");

WriteLiteral(" data-payment-type=\"gift-card\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"gift-card number item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Gift Card Number</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui action fluid input\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"GiftCardNumberInputText\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"ui icon blue button\"");

WriteLiteral(" onclick=\'$(\".ui.gift.card.modal\").modal(\"show\");\'");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"search icon\"");

WriteLiteral("></i>\r\n                        </button>\r\n                    </div>\r\n           " +
"     </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"gift-card balance item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Gift Card Balance</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" id=\"GiftCardNumberBalanceInputText\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    " +
"<div");

WriteLiteral(" class=\"one summary items\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"customer item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Customer</div>\r\n            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"ui fluid customer search\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"ui left icon fluid input\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"CustomerInputText\"");

WriteLiteral(" class=\"prompt\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"search grey icon\"");

WriteLiteral("></i>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n  " +
"      </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"three summary items\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"coupon code item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Coupon Code</div>\r\n            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"\"");

WriteLiteral(" id=\"CouponCodeInputText\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"discount type item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Discount Type</div>\r\n            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"DiscountTypeSelect\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">Rate</option>\r\n                    <option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">Amount</option>\r\n                </select>\r\n            </div>\r\n        </div>\r\n" +
"        <div");

WriteLiteral(" class=\"discount item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Discount</div>\r\n            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" id=\"DiscountInputText\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"value date item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Value Date</div>\r\n            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" id=\"ValueDateInputText\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"book date item\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Book Date</div>\r\n            <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"date\"");

WriteLiteral(" id=\"BookDateInputText\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <a");

WriteLiteral(" class=\"show more anchor\"");

WriteLiteral(">Show More</a>\r\n    <div");

WriteLiteral(" class=\"more\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"one summary items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"cost center item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Cost Center</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"CostCenterSelect\"");

WriteLiteral("></select>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <" +
"div");

WriteLiteral(" class=\"one summary items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"shipping company item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Shipper</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" class=\"ui inverted fluid dropdown\"");

WriteLiteral(" id=\"ShipperSelect\"");

WriteLiteral("></select>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <" +
"div");

WriteLiteral(" class=\"two summary items\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"reference number item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Ref#</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ReferenceNumberInputText\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"memo item\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"description\"");

WriteLiteral(">Memo</div>\r\n                <div");

WriteLiteral(" class=\"control\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"StatementReferenceInputText\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <a");

WriteLiteral(" class=\"show less anchor\"");

WriteLiteral(">Show Less</a>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"ui one column padded grid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"column\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"ui big green button\"");

WriteLiteral(" id=\"CheckoutButton\"");

WriteLiteral(">Checkout</button>\r\n\r\n            <div");

WriteLiteral(" class=\"ticket panel\"");

WriteLiteral(">\r\n                <iframe");

WriteLiteral(" id=\"TicketIframe\"");

WriteLiteral("></iframe>\r\n                <button");

WriteLiteral(" class=\"ui blue circular button\"");

WriteLiteral(" onclick=\"$(\'#TicketIframe\').get(0).contentWindow.print();\"");

WriteLiteral(" id=\"PrintButton\"");

WriteLiteral(">Print</button>\r\n                <button");

WriteLiteral(" class=\"ui red  circular button\"");

WriteLiteral(" onclick=\"$(\'.ticket.panel\').hide();\"");

WriteLiteral(">Hide</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script" +
">\r\n    function getLocalStorageKey(id) {\r\n        return \"posTab\" + id;\r\n    };\r" +
"\n\r\n    function getModel() {\r\n        function getDetails() {\r\n            const" +
" items = $(\"#SalesItems .item\");\r\n            var model = [];\r\n\r\n            $.e" +
"ach(items, function () {\r\n                const el = $(this);\r\n                c" +
"onst itemId = parseInt(el.attr(\"data-item-id\"));\r\n                const quantity" +
" = window.parseFloat2(el.find(\"input.quantity\").val());\r\n                const u" +
"nitId = parseInt(el.find(\"select.unit\").val());\r\n                const price = w" +
"indow.parseFloat2(el.find(\"input.price\").val() || 0);\r\n                const dis" +
"countRate = window.parseFloat2(el.find(\"input.discount\").val() || 0);\r\n         " +
"       const discount = (price * quantity) * (discountRate / 100);\r\n\r\n          " +
"      model.push({\r\n                    StoreId: $(\"#StoreSelect\").val(),\r\n     " +
"               ItemId: itemId,\r\n                    Quantity: quantity,\r\n       " +
"             UnitId: unitId,\r\n                    Price: price,\r\n               " +
"     DiscountRate: discountRate,\r\n                    Discount: discount\r\n      " +
"          });\r\n            });\r\n\r\n            return model;\r\n        };\r\n\r\n     " +
"   //Cash\r\n        const tender = window.parseFloat2($(\"#TenderInputText\").val()" +
");\r\n        const change = window.parseFloat2($(\"#ChangeInputText\").val());\r\n\r\n " +
"       //Credit\r\n        const counterId = parseInt($(\"#CounterSelect\").val()) |" +
"| null;\r\n        const paymentTermId = parseInt($(\"#PaymentTermSelect\").val()) |" +
"| null;\r\n\r\n        //Check\r\n        const checkAmount = window.parseFloat2($(\"#C" +
"heckAmountInputText\").val()) || null;\r\n        const bankName = $(\"#BankNameInpu" +
"tText\").val();\r\n        const checkNumber = $(\"#CheckNumberInputText\").val();\r\n " +
"       const checkDate = $(\"#CheckDateInputText\").datepicker(\"getDate\");\r\n\r\n    " +
"    //Gift Card\r\n        const giftCardNumber = $(\"#GiftCardNumberInputText\").va" +
"l();\r\n\r\n\r\n        //Discount Coupon\r\n        const couponCode = $(\"#CouponCodeIn" +
"putText\").val();\r\n\r\n        //Discount\r\n        const discountType = $(\"#Discoun" +
"tTypeSelect\").val();\r\n        const discount = window.parseFloat2($(\"#DiscountIn" +
"putText\").val());\r\n\r\n        const valueDate = $(\"#ValueDateInputText\").datepick" +
"er(\"getDate\");\r\n        const bookDate = $(\"#BookDateInputText\").datepicker(\"get" +
"Date\");\r\n        const costCenterId = parseInt($(\"#CostCenterSelect\").val()) || " +
"null;\r\n        const referenceNumber = $(\"#ReferenceNumberInputText\").val();\r\n  " +
"      const statementReference = $(\"#StatementReferenceInputText\").val();\r\n     " +
"   const customerId = parseInt($(\"#CustomerInputText\").attr(\"data-customer-id\"))" +
" || null;\r\n        const customerName = $(\"#CustomerInputText\").val();\r\n        " +
"const priceTypeId = $(\"#PriceTypeSelect\").val();\r\n        const shipperId = $(\"#" +
"ShipperSelect\").val();\r\n        const storeId = $(\"#StoreSelect\").val();\r\n      " +
"  const details = getDetails();\r\n        const quotationId = parseInt(window.get" +
"QueryStringByName(\"QuotationId\")) || null;\r\n        const orderId = parseInt(win" +
"dow.getQueryStringByName(\"OrderId\")) || null;\r\n\r\n        return {\r\n            T" +
"ender: tender,\r\n            Change: change,\r\n            PaymentTermId: paymentT" +
"ermId,\r\n            CheckAmount: checkAmount,\r\n            CheckBankName: bankNa" +
"me,\r\n            CheckNumber: checkNumber,\r\n            CheckDate: checkDate,\r\n " +
"           CounterId: counterId,\r\n            GiftCardNumber: giftCardNumber,\r\n " +
"           CouponCode: couponCode,\r\n            DiscountType: discountType,\r\n   " +
"         IsFlatDiscount: discountType === 2,\r\n            Discount: discount,\r\n " +
"           ValueDate: valueDate,\r\n            BookDate: bookDate,\r\n            C" +
"ostCenterId: costCenterId,\r\n            ReferenceNumber: referenceNumber,\r\n     " +
"       StatementReference: statementReference,\r\n            CustomerId: customer" +
"Id,\r\n            CustomerName: customerName,\r\n            PriceTypeId: priceType" +
"Id,\r\n            ShipperId: shipperId,\r\n            StoreId: storeId,\r\n         " +
"   Details: details,\r\n            SalesQuotationId: quotationId,\r\n            Sa" +
"lesOrderId: orderId\r\n        };\r\n    };\r\n\r\n    function getModelById(id) {\r\n    " +
"    const key = getLocalStorageKey(id);\r\n        const item = localStorage.getIt" +
"em(key);\r\n\r\n        if (item) {\r\n            return JSON.parse(item);\r\n        }" +
";\r\n\r\n        return null;\r\n    };\r\n\r\n    function removeModelById(id) {\r\n       " +
" const key = getLocalStorageKey(id);\r\n        localStorage.removeItem(key);\r\n   " +
" };\r\n\r\n    function clearState() {\r\n        $.each(localStorage, function (key) " +
"{\r\n            if (key.substr(0, 6) === \"posTab\") {\r\n                localStorag" +
"e.removeItem(key);\r\n            };\r\n        });\r\n    };\r\n    clearState();\r\n\r\n  " +
"  function getSelectedTabId() {\r\n        const id = parseInt($(\".tabs .selected." +
"item:not(.new)\").html());\r\n        return id;\r\n    };\r\n\r\n    function loadState(" +
") {\r\n        const id = getSelectedTabId();\r\n\r\n        if (id) {\r\n            lo" +
"adModelById(id);\r\n        };\r\n    };\r\n\r\n    function saveState() {\r\n        cons" +
"t id = getSelectedTabId();\r\n\r\n        if (!id) {\r\n            window.displayMess" +
"age(\"Please select a tab\");\r\n            return;\r\n        };\r\n\r\n        const mo" +
"del = window.getModel();\r\n        const key = getLocalStorageKey(id);\r\n        l" +
"ocalStorage.setItem(key, JSON.stringify(model));\r\n    };\r\n\r\n    function removeS" +
"tate() {\r\n        const id = getSelectedTabId();\r\n\r\n        if (id) {\r\n         " +
"   removeModelById(id);\r\n        };\r\n    };\r\n\r\n    function loadModelData(model)" +
" {\r\n        if (!model) {\r\n            return;\r\n        };\r\n\r\n        window.cle" +
"arScreen();\r\n\r\n\r\n        $(\"#TenderInputText\").val(model.Tender);\r\n        $(\"#C" +
"hangeInputText\").val(model.Change);\r\n        $(\"#PaymentTermSelect\").dropdown(\"s" +
"et selected\", model.PaymentTermId);\r\n        $(\"#CounterSelect\").dropdown(\"set s" +
"elected\", model.CounterId);\r\n\r\n        $(\"#CheckAmountInputText\").val(model.Chec" +
"kAmount);\r\n        $(\"#BankNameInputText\").val(model.CheckBankName);\r\n        $(" +
"\"#CheckNumberInputText\").val(model.CheckNumber);\r\n\r\n        if (model.CheckDate)" +
" {\r\n            $(\"#CheckDateInputText\").datepicker(\"setDate\", new Date(model.Ch" +
"eckDate));\r\n        };\r\n\r\n\r\n        $(\"#GiftCardNumberInputText\").val(model.Gift" +
"CardNumber).trigger(\"change\");\r\n        $(\"#CouponCodeInputText\").val(model.Coup" +
"onCode);\r\n        $(\"#DiscountTypeSelect\").dropdown(\"set selected\", model.Discou" +
"ntType);\r\n        $(\"#DiscountInputText\").val(model.Discount);\r\n\r\n        if (mo" +
"del.ValueDate) {\r\n            $(\"#ValueDateInputText\").datepicker(\"setDate\", new" +
" Date(model.ValueDate));\r\n        };\r\n\r\n        if (model.BookDate) {\r\n         " +
"   $(\"#BookDateInputText\").datepicker(\"setDate\", new Date(model.BookDate));\r\n   " +
"     };\r\n\r\n        $(\"#CostCenterSelect\").dropdown(\"set selected\", model.CostCen" +
"terId);\r\n        $(\"#ReferenceNumberInputText\").val(model.ReferenceNumber);\r\n   " +
"     $(\"#StatementReferenceInputText\").val(model.StatementReference);\r\n\r\n       " +
" $(\"#CustomerInputText\").attr(\"data-customer-id\", model.CustomerId).val(model.Cu" +
"stomerCode);\r\n        \r\n        if (model.PriceTypeId) {\r\n            $(\"#PriceT" +
"ypeSelect\").dropdown(\"set selected\", model.PriceTypeId);\r\n        };\r\n\r\n        " +
"if (model.ShipperId) {\r\n            $(\"#ShipperSelect\").dropdown(\"set selected\"," +
" model.ShipperId);\r\n        };\r\n\r\n        if (model.StoreId) {\r\n            $(\"#" +
"StoreSelect\").dropdown(\"set selected\", model.StoreId);\r\n        };\r\n\r\n\r\n        " +
"$.each(model.Details, function () {\r\n            const lineItem = this;\r\n\r\n     " +
"       const itemId = lineItem.ItemId;\r\n            const selector = \"#POSItemLi" +
"st .item[data-item-id=\" + itemId + \"]\";\r\n            $(selector).trigger(\"click\"" +
");\r\n        });\r\n    };\r\n\r\n    function loadModelById(id) {\r\n        const model" +
" = getModelById(id);\r\n        loadModelData(model);\r\n    };\r\n</script>\r\n<script>" +
"\r\n    function showTicket(id) {\r\n        const url = \"/dashboard/sales/ticket/\" " +
"+ id;\r\n\r\n        $(\"#TicketIframe\").attr(\"src\", url);\r\n        $(\".ticket.panel\"" +
").show();\r\n    };\r\n\r\n    $(\"#TenderInputText\").on(\"keyup\", function () {\r\n      " +
"  const total = window.parseFloat2($(\".amount.item .money\").text());\r\n        co" +
"nst tender = window.parseFloat2($(this).val());\r\n\r\n        var change = tender -" +
" total;\r\n\r\n        if (change < 0) {\r\n            change = \"ERROR\";\r\n        };\r" +
"\n\r\n        $(\"#ChangeInputText\").val(change);\r\n    });\r\n\r\n    $(\"#CheckoutButton" +
"\").unbind(\"click\").bind(\"click\", function () {\r\n        function request(model) " +
"{\r\n            const url = \"/dashboard/sales/tasks/entry/new\";\r\n            cons" +
"t data = JSON.stringify(model);\r\n            return window.getAjaxRequest(url, \"" +
"POST\", data);\r\n        };\r\n\r\n        function validate() {\r\n            var tran" +
"sactionTotal = window.parseFloat2($(\"div.amount .money\").text());\r\n            v" +
"ar cashTender = window.parseFloat2($(\"#TenderInputText\").val());\r\n            va" +
"r paymentTerm = parseInt($(\"#PaymentTermSelect\").val()) || null;\r\n            va" +
"r checkAmount = window.parseFloat2($(\"#CheckAmountInputText\").val());\r\n         " +
"   var bankName = $(\"#BankNameInputText\").val();\r\n            var checkDate = $(" +
"\"#CheckDateInputText\").datepicker(\"getDate\");\r\n            var checkNumber = $(\"" +
"#CheckNumberInputText\").val();\r\n            var giftCardNumber = $(\"#GiftCardNum" +
"berInputText\").val();\r\n            var giftCardBalance = $(\"#GiftCardNumberBalan" +
"ceInputText\").val();\r\n\r\n            if (cashTender >= transactionTotal) {\r\n     " +
"           //Cash Transaction\r\n\r\n                $(\"#CheckAmountInputText\").val(" +
"\"\");\r\n                $(\"#BankNameInputText\").val(\"\");\r\n                $(\"#Chec" +
"kDateInputText\").val(\"\");\r\n                $(\"#CheckNumberInputText\").val(\"\");\r\n" +
"                $(\"#PaymentTermSelect\").dropdown(\"set selected\", \"Select\");\r\n   " +
"             $(\"#GiftCardNumberInputText\").val(\"\");\r\n                $(\"#GiftCar" +
"dNumberBalanceInputText\").val(\"\");\r\n                return true;\r\n            };" +
"\r\n\r\n            if (checkAmount >= transactionTotal) {\r\n                //Paid v" +
"ia Check/Cheque\r\n                if (!bankName) {\r\n                    window.di" +
"splayMessage(\"Please enter the bank name.\");\r\n                    return false;\r" +
"\n                };\r\n\r\n                if (!checkNumber) {\r\n                    " +
"window.displayMessage(\"Please enter the check number.\");\r\n                    re" +
"turn false;\r\n                };\r\n\r\n                if (!checkDate) {\r\n          " +
"          window.displayMessage(\"Please enter the check date.\");\r\n              " +
"      return false;\r\n                };\r\n\r\n                $(\"#TenderInputText\")" +
".val(\"\");\r\n                $(\"#ChangeInputText\").val(\"\");\r\n                $(\"#P" +
"aymentTermSelect\").dropdown(\"set selected\", \"Select\");\r\n                $(\"#Gift" +
"CardNumberInputText\").val(\"\");\r\n                $(\"#GiftCardNumberBalanceInputTe" +
"xt\").val(\"\");\r\n\r\n\r\n                return true;\r\n            };\r\n\r\n            i" +
"f (giftCardBalance >= transactionTotal) {\r\n                //Paid via Gift Card\r" +
"\n\r\n                if (!giftCardNumber) {\r\n                    window.displayMes" +
"sage(\"Please enter the gift card number.\");\r\n                    return false;\r\n" +
"                };\r\n\r\n                $(\"#TenderInputText\").val(\"\");\r\n          " +
"      $(\"#ChangeInputText\").val(\"\");\r\n                $(\"#CheckAmountInputText\")" +
".val(\"\");\r\n                $(\"#BankNameInputText\").val(\"\");\r\n                $(\"" +
"#CheckDateInputText\").val(\"\");\r\n                $(\"#CheckNumberInputText\").val(\"" +
"\");\r\n                $(\"#PaymentTermSelect\").dropdown(\"set selected\", \"Select\");" +
"\r\n\r\n                return true;\r\n            };\r\n\r\n            //Credit transac" +
"tion\r\n            $(\"#TenderInputText\").val(\"\");\r\n            $(\"#ChangeInputTex" +
"t\").val(\"\");\r\n            $(\"#CheckAmountInputText\").val(\"\");\r\n            $(\"#B" +
"ankNameInputText\").val(\"\");\r\n            $(\"#CheckDateInputText\").val(\"\");\r\n    " +
"        $(\"#CheckNumberInputText\").val(\"\");\r\n            $(\"#GiftCardNumberInput" +
"Text\").val(\"\");\r\n            $(\"#GiftCardNumberBalanceInputText\").val(\"\");\r\n\r\n  " +
"          if (!paymentTerm) {\r\n                window.displayMessage(\"Please sel" +
"ect a payment term.\");\r\n                return false;\r\n            };\r\n\r\n       " +
"     return true;\r\n        };\r\n\r\n        const isValid = validate();\r\n\r\n        " +
"if (!isValid) {\r\n            return;\r\n        };\r\n\r\n        const model = window" +
".getModel();\r\n\r\n        if (!model.Details.length) {\r\n            window.display" +
"Message(\"Please select an item.\");\r\n            return;\r\n        };\r\n\r\n        c" +
"onst confirmed = confirm(\"Are you sure\");\r\n\r\n        if (!confirmed) {\r\n        " +
"    return;\r\n        };\r\n\r\n\r\n        $(\"#CheckoutButton\").addClass(\"loading\");\r\n" +
"\r\n        const ajax = request(model);\r\n\r\n        ajax.success(function (respons" +
"e) {\r\n            const id = response;\r\n            window.clearScreen();\r\n\r\n   " +
"         window.showTicket(id);\r\n            $(\"#CheckoutButton\").removeClass(\"l" +
"oading\");\r\n        });\r\n\r\n        ajax.fail(function (xhr) {\r\n            $(\"#Ch" +
"eckoutButton\").removeClass(\"loading\");\r\n            window.displayMessage(JSON.s" +
"tringify(xhr));\r\n        });\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
