#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Loyalty/GiftCards/AddFund/Index.cshtml")]
    public partial class _Views_Loyalty_GiftCards_AddFund_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Loyalty_GiftCards_AddFund_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Loyalty\GiftCards\AddFund\Index.cshtml"
  
    ViewBag.Title = "Gift Card Funds";
    Layout = ViewBag.SalesLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .modal iframe {\r\n        width: 100%;\r\n        border: none;\r\n    " +
"    height: 700px;\r\n    }\r\n</style>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<div");

WriteLiteral(" class=\"ui attached page segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Gift Card Funds</div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui basic buttons\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" id=\"AddNewButton\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(" style=\"\"");

WriteLiteral(" href=\"/dashboard/loyalty/tasks/gift-cards/add-fund/entry\"");

WriteLiteral(">\r\n            Add New\r\n        </a>\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"ui icon top left pointing dropdown basic button\"");

WriteLiteral(" id=\"ExportDropDown\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">\r\n            <span>\r\n                Export\r\n            </span>\r\n            <" +
"div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n                    Export This Document\r\n                </div>\r\n            " +
"    <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createDoc();\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file word outline blue icon\"");

WriteLiteral("></i> Export to Doc\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createXls();\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file excel outline green icon\"");

WriteLiteral("></i> Export to Excel\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createPDF();\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file pdf outline red icon\"");

WriteLiteral("></i> Export to PDF\r\n                </a>\r\n            </div>\r\n        </div>\r\n  " +
"      <a");

WriteLiteral(" id=\"PrintButton\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"print()\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">\r\n            Print\r\n        </a>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui stackable form segment\"");

WriteLiteral(" id=\"Annotation\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"eight fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"date\"");

WriteLiteral("  data-persist");

WriteLiteral(" placeholder=\"From\"");

WriteLiteral(" id=\"FromInputDate\"");

WriteLiteral(" title=\"From\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"date\"");

WriteLiteral("  data-persist");

WriteLiteral(" placeholder=\"To\"");

WriteLiteral(" id=\"ToInputDate\"");

WriteLiteral(" title=\"To\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"TranCode\"");

WriteLiteral(" id=\"TranCodeInputText\"");

WriteLiteral(" title=\"TranCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Customer\"");

WriteLiteral(" id=\"CustomerNameInputText\"");

WriteLiteral(" title=\"Customer\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"ReferenceNumber\"");

WriteLiteral(" id=\"ReferenceNumberInputText\"");

WriteLiteral(" title=\"ReferenceNumber\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"StatementReference\"");

WriteLiteral(" id=\"StatementReferenceInputText\"");

WriteLiteral(" title=\"StatementReference\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"PostedBy\"");

WriteLiteral(" id=\"PostedByInputText\"");

WriteLiteral(" title=\"PostedBy\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Office\"");

WriteLiteral(" id=\"OfficeInputText\"");

WriteLiteral(" title=\"Office\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"eight fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Status\"");

WriteLiteral(" id=\"StatusInputText\"");

WriteLiteral(" title=\"Status\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"VerifiedBy\"");

WriteLiteral(" id=\"VerifiedByInputText\"");

WriteLiteral(" title=\"VerifiedBy\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Reason\"");

WriteLiteral(" id=\"ReasonInputText\"");

WriteLiteral(" title=\"Reason\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field hidden\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"UserId\"");

WriteLiteral(" id=\"UserIdInputText\"");

WriteLiteral(" title=\"UserId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field hidden\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"OfficeId\"");

WriteLiteral(" id=\"OfficeIdInputText\"");

WriteLiteral(" title=\"OfficeId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" id=\"ShowButton\"");

WriteLiteral(">Show</div>\r\n            </div>\r\n        </div>\r\n\r\n\r\n    </div>\r\n\r\n    <table");

WriteLiteral(" id=\"SalesView\"");

WriteLiteral(" class=\"ui table segment\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>Actions</th>
                <th>Select</th>
                <th>TranId</th>
                <th>TranCode</th>
                <th>Value Date</th>
                <th>Book Date</th>
                <th>Customer Name</th>
                <th>Amount</th>
                <th>Ref#</th>
                <th>Statement Reference</th>
                <th>Posted By</th>
                <th>Office</th>
                <th>Status</th>
                <th>Verified By</th>
                <th>Verified On</th>
                <th>Reason</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div");

WriteLiteral(" class=\"ui large advice modal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n    <iframe></iframe>\r\n</div>\r\n<script>\r\n    function displayTable(target," +
" model) {\r\n        target.find(\"tbody\").html(\"\");\r\n        function getCell(text" +
") {\r\n            const cell = $(\"<td />\");\r\n\r\n            cell.text(text || \"\");" +
"\r\n\r\n            return cell;\r\n        };\r\n\r\n        function getActionCell(tranI" +
"d) {\r\n            const cell = $(\"<td />\");\r\n\r\n            const checklistAnchor" +
" = $(\"<a title=\'Checklist Window\'><i class=\'list icon\'></i></a>\");\r\n            " +
"checklistAnchor.attr(\"href\", \"/dashboard/sales/tasks/entry/checklist/\" + tranId)" +
";\r\n\r\n            const journalAdviceAnchor = $(\"<a title=\'View Journal Advice\'><" +
"i class=\'print icon\'></i></a>\");\r\n            journalAdviceAnchor.attr(\"href\", \"" +
"javascript:void(0);\");\r\n            journalAdviceAnchor.attr(\"onclick\", \"showJou" +
"rnalAdvice(\" + tranId + \");\");\r\n\r\n            const salesAdvice = $(\"<a title=\'V" +
"iew Sales Invoice\'><i class=\'zoom icon\'></i></a>\");\r\n            salesAdvice.att" +
"r(\"href\", \"javascript:void(0);\");\r\n\r\n\r\n            cell.append(checklistAnchor);" +
"\r\n            cell.append(journalAdviceAnchor);\r\n            cell.append(salesAd" +
"vice);\r\n            return cell;\r\n        };\r\n\r\n        function getSelectionCel" +
"l() {\r\n            const cell = $(\"<td />\");\r\n            const checkbox = $(\"<d" +
"iv class=\'ui toggle checkbox\'/>\");\r\n            const input = $(\"<input type=\'ch" +
"eckbox\' />\");\r\n            const label = $(\"<label />\");\r\n\r\n            checkbox" +
".append(input);\r\n            checkbox.append(label);\r\n\r\n            cell.append(" +
"checkbox);\r\n\r\n            return cell;\r\n        };\r\n\r\n        $.each(model, func" +
"tion () {\r\n            const item = this;\r\n\r\n            const row = $(\"<tr />\")" +
";\r\n\r\n            row.append(getActionCell(item.transaction_master_id));\r\n       " +
"     row.append(getSelectionCell(item.transaction_master_id));\r\n            row." +
"append(getCell(item.transaction_master_id));\r\n            row.append(getCell(ite" +
"m.transaction_code));\r\n            row.append(getCell(item.value_date));\r\n      " +
"      row.append(getCell(item.book_date));\r\n            row.append(getCell(item." +
"customer_name));\r\n            row.append(getCell(item.amount));\r\n            row" +
".append(getCell(item.reference_number));\r\n            row.append(getCell(item.st" +
"atement_reference));\r\n            row.append(getCell(item.posted_by));\r\n        " +
"    row.append(getCell(item.office_name));\r\n            row.append(getCell(item." +
"status));\r\n            row.append(getCell(item.verified_by));\r\n            row.a" +
"ppend(getCell(item.last_verified_on));\r\n            row.append(getCell(item.veri" +
"fication_reason));\r\n\r\n            target.find(\"tbody\").append(row);\r\n        });" +
"\r\n    };\r\n    function processQuery() {\r\n        function getModel() {\r\n        " +
"    const model = window.serializeForm($(\"#Annotation\"));\r\n\r\n            const f" +
"ilters = [];\r\n\r\n            filters.push(window.getAjaxColumnFilter(\"WHERE\", \"of" +
"fice_id\", \"int\", window.FilterConditions.IsEqualTo, window.metaView.OfficeId));\r" +
"\n            filters.push(window.getAjaxColumnFilter(\"WHERE\", \"value_date\", \"Sys" +
"tem.DateTime\", window.FilterConditions.IsGreaterThanEqualTo, model.From));\r\n    " +
"        filters.push(window.getAjaxColumnFilter(\"WHERE\", \"value_date\", \"System.D" +
"ateTime\", window.FilterConditions.IsLessThanEqualTo, model.To));\r\n            fi" +
"lters.push(window.getAjaxColumnFilter(\"WHERE\", \"transaction_code\", \"string\", win" +
"dow.FilterConditions.IsLike, model.TranCode));\r\n            filters.push(window." +
"getAjaxColumnFilter(\"WHERE\", \"customer_name\", \"string\", window.FilterConditions." +
"IsLike, model.CustomerName));\r\n            filters.push(window.getAjaxColumnFilt" +
"er(\"WHERE\", \"reference_number\", \"string\", window.FilterConditions.IsLike, model." +
"ReferenceNumber));\r\n            filters.push(window.getAjaxColumnFilter(\"WHERE\"," +
" \"statement_reference\", \"string\", window.FilterConditions.IsLike, model.Statemen" +
"tReference));\r\n            filters.push(window.getAjaxColumnFilter(\"WHERE\", \"pos" +
"ted_by\", \"string\", window.FilterConditions.IsLike, model.PostedBy));\r\n          " +
"  filters.push(window.getAjaxColumnFilter(\"WHERE\", \"office_name\", \"string\", wind" +
"ow.FilterConditions.IsLike, model.Office));\r\n            filters.push(window.get" +
"AjaxColumnFilter(\"WHERE\", \"status\", \"string\", window.FilterConditions.IsLike, mo" +
"del.Status));\r\n            filters.push(window.getAjaxColumnFilter(\"WHERE\", \"ver" +
"ified_by\", \"string\", window.FilterConditions.IsLike, model.VerifiedBy));\r\n      " +
"      filters.push(window.getAjaxColumnFilter(\"WHERE\", \"verification_reason\", \"s" +
"tring\", window.FilterConditions.IsLike, model.Reason));\r\n\r\n            \r\n       " +
"     return filters;\r\n        };\r\n\r\n        function displayGrid(target) {\r\n    " +
"        function request(model) {\r\n                const url = \"/api/views/sales" +
"/gift-card-transaction-view/get-where/-1\";\r\n                const data = JSON.st" +
"ringify(model);\r\n                return window.getAjaxRequest(url, \"POST\", data)" +
";\r\n            };\r\n\r\n            const model = getModel();\r\n\r\n            const " +
"ajax = request(model);\r\n\r\n            ajax.success(function (response) {\r\n      " +
"          displayTable(target, response);\r\n                target.removeClass(\"l" +
"oading\");\r\n            });\r\n\r\n            ajax.fail(function (xhr) {\r\n          " +
"      alert(JSON.stringify(xhr));\r\n            });\r\n        };\r\n\r\n        const " +
"view = $(\"#SalesView\").addClass(\"loading\");\r\n\r\n        displayGrid(view);\r\n    }" +
";\r\n\r\n    $(\"#ShowButton\").unbind(\"click\").bind(\"click\", function () {\r\n        p" +
"rocessQuery();\r\n    });\r\n\r\n    loadDatepicker();\r\n\r\n    \r\n    function showJourn" +
"alAdvice(tranId) {\r\n        $(\".modal iframe\").attr(\"src\", \"/dashboard/reports/s" +
"ource/Areas/MixERP.Finance/Reports/JournalEntry.xml?transaction_master_id=\" + tr" +
"anId);\r\n\r\n        setTimeout(function () {\r\n            $(\".advice.modal\")\r\n    " +
"            .modal(\'setting\', \'transition\', \'horizontal flip\')\r\n                " +
".modal(\"show\");\r\n\r\n        }, 300);\r\n    };\r\n\r\n    $(\"#ReturnButton\").click(func" +
"tion() {\r\n        function getSelectedItem() {\r\n            const selected = $(\"" +
"#SalesView\").find(\"input:checked\").first();\r\n\r\n            if (selected.length) " +
"{\r\n                const row = selected.parent().parent().parent();\r\n           " +
"     const id = row.find(\"td:nth-child(3)\").html();\r\n                return pars" +
"eInt(id);\r\n            };\r\n\r\n            return 0;\r\n        };\r\n\r\n        const " +
"selected = getSelectedItem();\r\n        if (selected) {\r\n            const url = " +
"\"/dashboard/sales/tasks/entry/new?Type=Return&TransactionMasterId=\" + selected;\r" +
"\n            document.location = url;\r\n            return;\r\n        };\r\n\r\n      " +
"  window.displayMessage(\"Please select an item from the grid.\");\r\n    });\r\n\r\n   " +
" setTimeout(function () {\r\n        processQuery();\r\n    }, 1000);\r\n</script>");

        }
    }
}
#pragma warning restore 1591
