#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
    using Frapid.ApplicationState.Cache;
    
    #line default
    #line hidden
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/ClosingCash/Index.cshtml")]
    public partial class _Views_Tasks_ClosingCash_Index_cshtml : System.Web.Mvc.WebViewPage<MixERP.Sales.ViewModels.ClosingCashViewModel>
    {
        public _Views_Tasks_ClosingCash_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = ViewBag.Layout;
    decimal tenderTotal = Model.SalesView.Sum(x => x.Tender);
    decimal changeTotal = Model.SalesView.Sum(x => x.Change);
    decimal total = Model.SalesView.Sum(x => x.TotalAmount);
    decimal submittedAmount = total;
    string submittedTo = string.Empty;
    string memo = string.Empty;
    bool submitted = false;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 16 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
  
    if (Model.ClosingCashInfo != null && Model.ClosingCashInfo.ClosingCashId > 0)
    {
        submitted = true;
        submittedAmount = Model.ClosingCashInfo.SubmittedCash;
        submittedTo = Model.ClosingCashInfo.SubmittedTo;
        memo = Model.ClosingCashInfo.Memo;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n\r\n<style>\r\n    .very.relaxed.segment { padding: 4em; }\r\n\r\n    ");

WriteLiteral(@"@media print {
        .no.print { display: none !important; }

        table { page-break-inside: auto !important; }

        tr {
            page-break-after: auto !important;
            page-break-inside: avoid !important;
        }

        thead { display: table-header-group !important; }

        tfoot { display: table-footer-group !important; }

        .page.break { page-break-before: always; }
    }

    ");

WriteLiteral(@"@media screen {
        .no.screen { display: none !important; }
    }

    #SubmittedCashInputText.selected {
        border: 1px solid #BD6711;
        color: #BD6711;
    }

    .denomination .field,
    .denomination .multiply,
    .denomination .text,
    .denomination .equals {
        display: inline-block;
        padding: 0.2em 0.5em;
    }


    .denomination .text {
        text-align: right;
        width: 40px;
    }
</style>
<div");

WriteLiteral(" class=\"ui attached very relaxed segment\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">\r\n    EOD Cash\r\n    <div");

WriteLiteral(" class=\"ui teal label\"");

WriteLiteral(">");

            
            #line 75 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                          Write(Model.OpeningCashInfo.TransactionDate.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n</div>\r\n<div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" class=\"ui positive message\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 80 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
Write(AppUsers.GetCurrent().Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"ui stackable grid eod no print cash\"");

WriteLiteral(" style=\"padding: 1em 0;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"eight wide column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Denominations</div>\r\n        <div");

WriteLiteral(" class=\"denominations\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno1000InputText\"");

WriteLiteral(" data-value=\"1000\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2592), Tuple.Create("\"", 2631)
            
            #line 88 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                       , Tuple.Create(Tuple.Create("", 2600), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno1000
            
            #line default
            #line hidden
, 2600), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 88 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                                     Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">1000</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno1000TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno500InputText\"");

WriteLiteral(" data-value=\"500\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3195), Tuple.Create("\"", 3233)
            
            #line 99 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                     , Tuple.Create(Tuple.Create("", 3203), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno500
            
            #line default
            #line hidden
, 3203), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 99 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                                  Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">500</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno500TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno250InputText\"");

WriteLiteral(" data-value=\"250\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3795), Tuple.Create("\"", 3833)
            
            #line 110 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                     , Tuple.Create(Tuple.Create("", 3803), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno250
            
            #line default
            #line hidden
, 3803), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 110 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                                  Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">250</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno250TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno200InputText\"");

WriteLiteral(" data-value=\"200\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4395), Tuple.Create("\"", 4433)
            
            #line 121 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                     , Tuple.Create(Tuple.Create("", 4403), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno200
            
            #line default
            #line hidden
, 4403), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 121 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                                  Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">200</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno200TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno100InputText\"");

WriteLiteral(" data-value=\"100\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4995), Tuple.Create("\"", 5033)
            
            #line 132 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                     , Tuple.Create(Tuple.Create("", 5003), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno100
            
            #line default
            #line hidden
, 5003), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 132 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                                  Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">100</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno100TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno50InputText\"");

WriteLiteral(" data-value=\"50\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5593), Tuple.Create("\"", 5630)
            
            #line 143 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                   , Tuple.Create(Tuple.Create("", 5601), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno50
            
            #line default
            #line hidden
, 5601), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 143 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                               Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">50</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno50TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno25InputText\"");

WriteLiteral(" data-value=\"25\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6188), Tuple.Create("\"", 6225)
            
            #line 154 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                   , Tuple.Create(Tuple.Create("", 6196), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno25
            
            #line default
            #line hidden
, 6196), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 154 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                               Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">25</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno25TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno20InputText\"");

WriteLiteral(" data-value=\"20\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6783), Tuple.Create("\"", 6820)
            
            #line 165 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                   , Tuple.Create(Tuple.Create("", 6791), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno20
            
            #line default
            #line hidden
, 6791), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 165 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                               Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">20</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno20TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno10InputText\"");

WriteLiteral(" data-value=\"10\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7378), Tuple.Create("\"", 7415)
            
            #line 176 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                   , Tuple.Create(Tuple.Create("", 7386), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno10
            
            #line default
            #line hidden
, 7386), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 176 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                               Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">10</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno10TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno5InputText\"");

WriteLiteral(" data-value=\"5\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7971), Tuple.Create("\"", 8007)
            
            #line 187 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                 , Tuple.Create(Tuple.Create("", 7979), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno5
            
            #line default
            #line hidden
, 7979), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 187 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                            Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">5</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno5TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno2InputText\"");

WriteLiteral(" data-value=\"2\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8561), Tuple.Create("\"", 8597)
            
            #line 198 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                 , Tuple.Create(Tuple.Create("", 8569), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno2
            
            #line default
            #line hidden
, 8569), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 198 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                            Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">2</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno2TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"integer\"");

WriteLiteral(" id=\"Deno1InputText\"");

WriteLiteral(" data-value=\"1\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9151), Tuple.Create("\"", 9187)
            
            #line 209 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                 , Tuple.Create(Tuple.Create("", 9159), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Deno1
            
            #line default
            #line hidden
, 9159), false)
);

WriteLiteral(" data-allow-edit=\"");

            
            #line 209 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                                            Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">1</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"Deno1TotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"denomination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui input field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" id=\"CoinsInputText\"");

WriteLiteral("\r\n                           data-value=\"1\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9769), Tuple.Create("\"", 9805)
            
            #line 221 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
, Tuple.Create(Tuple.Create("", 9777), Tuple.Create<System.Object, System.Int32>(Model.ClosingCashInfo.Coins
            
            #line default
            #line hidden
, 9777), false)
);

WriteLiteral(" \r\n                           data-allow-edit=\"");

            
            #line 222 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                        Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("/>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"multiply\"");

WriteLiteral(">x</div>\r\n                <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">Coins</div>\r\n                <div");

WriteLiteral(" class=\"equals\"");

WriteLiteral(">=</div>\r\n                <div");

WriteLiteral(" class=\"ui input total field\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" id=\"CoinsTotalInputText\"");

WriteLiteral("/>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <" +
"div");

WriteLiteral(" class=\"eight wide column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui header\"");

WriteLiteral(">Closing Summary</div>\r\n        <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"ui no print form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Today\'s Beginning Cash</label>\r\n                   " +
" <input");

WriteLiteral(" id=\"BodCashInputText\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10646), Tuple.Create("\"", 10698)
            
            #line 240 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                       , Tuple.Create(Tuple.Create("", 10654), Tuple.Create<System.Object, System.Int32>(Model.OpeningCashInfo.Amount.ToString("N2")
            
            #line default
            #line hidden
, 10654), false)
);

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Total</label>\r\n                    <input");

WriteLiteral(" id=\"TotalInputText\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10941), Tuple.Create("\"", 10970)
            
            #line 246 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
     , Tuple.Create(Tuple.Create("", 10949), Tuple.Create<System.Object, System.Int32>(total.ToString("N2")
            
            #line default
            #line hidden
, 10949), false)
);

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Submitted Cash</label>\r\n\r\n                    <inpu" +
"t");

WriteLiteral(" id=\"SubmittedCashInputText\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" readonly=\"\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create("\r\n                           value=\"", 11194), Tuple.Create("\"", 11261)
            
            #line 252 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
, Tuple.Create(Tuple.Create("", 11230), Tuple.Create<System.Object, System.Int32>(submittedAmount.ToString("N2")
            
            #line default
            #line hidden
, 11230), false)
);

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 252 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                    Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label>Submitted To</label>\r\n                <input");

WriteLiteral(" id=\"SubmittedToInputText\"");

WriteLiteral(" required=\"\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11511), Tuple.Create("\"", 11531)
            
            #line 257 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
, Tuple.Create(Tuple.Create("", 11519), Tuple.Create<System.Object, System.Int32>(submittedTo
            
            #line default
            #line hidden
, 11519), false)
);

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 257 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                                               Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label>Memo</label>\r\n                <textarea");

WriteLiteral(" id=\"MemoTextArea\"");

WriteLiteral(" rows=\"10\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 261 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                       Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">");

            
            #line 261 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                                     Write(memo);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n            </div>\r\n            <button");

WriteLiteral(" id=\"SaveButton\"");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 263 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                                                                             Write(!submitted);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">Save</button>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<table");

WriteLiteral(" class=\"ui celled compact striped table\"");

WriteLiteral(">\r\n    <caption>\r\n        Your Sales for ");

            
            #line 270 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                  Write(DateTime.Now.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </caption>\r\n    <tfoot>\r\n    <tr>\r\n        <th");

WriteLiteral(" colspan=\"6\"");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">Total</th>\r\n        <th");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">");

            
            #line 275 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                             Write(tenderTotal.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">");

            
            #line 276 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                             Write(changeTotal.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n        <th");

WriteLiteral(" class=\"warning right aligned\"");

WriteLiteral(">");

            
            #line 277 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                     Write(total.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n    </tr>\r\n    </tfoot>\r\n    <thead>\r\n    <tr>\r\n        <th>Id</th>\r\n     " +
"   <th>Inv#</th>\r\n        <th>Price Type</th>\r\n        <th>Counter</th>\r\n       " +
" <th>Customer</th>\r\n        <th>Coupon Code</th>\r\n        <th");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">Tender</th>\r\n        <th");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">Change</th>\r\n        <th");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">Sales</th>\r\n    </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 294 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 294 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
     foreach (var item in Model.SalesView.OrderBy(x => x.InvoiceNumber))
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>");

            
            #line 297 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
           Write(item.TransactionMasterId);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 298 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
           Write(item.InvoiceNumber);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 299 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
           Write(item.PriceTypeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 300 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
           Write(item.CounterName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 301 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
           Write(item.CustomerName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 302 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
           Write(item.CouponCode);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 302 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                             Write(item.CouponName);

            
            #line default
            #line hidden
WriteLiteral(")</td>\r\n            <td");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">");

            
            #line 303 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                 Write(item.Tender);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">");

            
            #line 304 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                 Write(item.Change);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td");

WriteLiteral(" class=\"right aligned\"");

WriteLiteral(">");

            
            #line 305 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
                                 Write(item.TotalAmount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n");

            
            #line 307 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n<table");

WriteLiteral(" class=\"ui no screen celled collapsing definition page break table\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th></th>\r\n        <th>Amount</th>\r\n    </tr>\r\n" +
"    </thead>\r\n    <tbody>\r\n    <tr>\r\n        <th>Opening Cash</th>\r\n        <td>" +
"");

            
            #line 321 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
       Write(Model.OpeningCashInfo.Amount.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <th>Total Sales</th>\r\n        <td>");

            
            #line 325 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
       Write(total.ToString("N2"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <th>Submitted Amount</th>\r\n        <td");

WriteLiteral(" class=\"submitted amount\"");

WriteLiteral("></td>\r\n    </tr>\r\n    </tbody>\r\n</table>\r\n\r\n<a");

WriteLiteral(" class=\"ui positive no print download button\"");

WriteAttribute("download", Tuple.Create(" download=\"", 13942), Tuple.Create("\"", 14051)
, Tuple.Create(Tuple.Create("", 13953), Tuple.Create("Sales-", 13953), true)
            
            #line 334 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
, Tuple.Create(Tuple.Create("", 13959), Tuple.Create<System.Object, System.Int32>(AppUsers.GetCurrent().Name
            
            #line default
            #line hidden
, 13959), false)
, Tuple.Create(Tuple.Create("", 13986), Tuple.Create("-", 13986), true)
            
            #line 334 "..\..\Views\Tasks\ClosingCash\Index.cshtml"
            , Tuple.Create(Tuple.Create("", 13987), Tuple.Create<System.Object, System.Int32>(Model.OpeningCashInfo.TransactionDate.ToShortDateString()
            
            #line default
            #line hidden
, 13987), false)
, Tuple.Create(Tuple.Create("", 14047), Tuple.Create(".csv", 14047), true)
);

WriteLiteral(">Export to Excel</a>\r\n</div>\r\n</div>\r\n\r\n<script>\r\n    function updateTotal() {\r\n " +
"       const candidates = $(\".denomination .ui.input.field:not(.total) input\");\r" +
"\n\r\n        var total = 0;\r\n\r\n        $.each(candidates, function() {\r\n          " +
"  const el = $(this);\r\n            const value = parseInt(el.attr(\"data-value\"))" +
" || 0;\r\n            const number = window.parseFloat2(el.val());\r\n\r\n            " +
"const result = value * number;\r\n\r\n            total += result;\r\n        });\r\n\r\n " +
"       $(\"#SubmittedCashInputText\").val(total).addClass(\"selected\");\r\n        $(" +
"\".submitted.Amount\").html(total);\r\n    };\r\n\r\n    (function() {\r\n        const ca" +
"ndidates = $(\"[data-allow-edit]\");\r\n\r\n        $.each(candidates, function() {\r\n " +
"           const el = $(this);\r\n\r\n            const allowEdit = el.attr(\"data-al" +
"low-edit\").toLowerCase() === \"true\";\r\n            el.prop(\"disabled\", !allowEdit" +
");\r\n        });\r\n\r\n        updateTotal();\r\n    })();\r\n\r\n    $(document).ready(fu" +
"nction() {\r\n        window.validator.initialize($(\".ui.form\"));\r\n        window." +
"setNumberFormat();\r\n    });\r\n\r\n    $(\"#SaveButton\").unbind(\"click\").bind(\"click\"" +
", function() {\r\n        function request(model) {\r\n            const url = \"/das" +
"hboard/sales/tasks/eod\";\r\n            const data = JSON.stringify(model);\r\n     " +
"       return window.getAjaxRequest(url, \"POST\", data);\r\n        };\r\n\r\n        c" +
"onst confirmed = confirm(\"Are you sure?\");\r\n\r\n        if (!confirmed) {\r\n       " +
"     return;\r\n        };\r\n\r\n        const model = window.serializeForm($(\".eod.c" +
"ash\"));\r\n        const total = parseFloat($(\"#TotalInputText\").val());\r\n\r\n      " +
"  if (parseFloat(model.SubmittedCash) !== total) {\r\n            window.displayMe" +
"ssage(\"The submitted amount must be equal to total amount.\");\r\n            retur" +
"n;\r\n        };\r\n\r\n        const ajax = request(model);\r\n\r\n        ajax.success(f" +
"unction() {\r\n            window.displaySuccess();\r\n            document.location" +
" = document.location;\r\n        });\r\n\r\n        ajax.fail(function(xhr) {\r\n       " +
"     alert(JSON.stringify(xhr));\r\n        });\r\n    });\r\n\r\n\r\n    $(\".denomination" +
" .ui.input.field:not(.total) input\").keyup(function() {\r\n        const el = $(th" +
"is);\r\n        const value = parseInt(el.attr(\"data-value\")) || 0;\r\n        const" +
" number = window.parseFloat2(el.val()) || 0;\r\n        const result = value * num" +
"ber;\r\n\r\n        const target = el.parent().parent().find(\".ui.input.total.field " +
"input\");\r\n        target.val(result);\r\n\r\n        updateTotal();\r\n    });\r\n\r\n    " +
"$(\".download.button\").click(function() {\r\n    });\r\n\r\n    function getTableInText" +
"() {\r\n        const headerCells = $(\"table:first thead tr th\");\r\n        const r" +
"ows = $(\"table:first tbody tr\");\r\n\r\n        var contents = \"\";\r\n\r\n        var me" +
"mbers = [];\r\n\r\n        $.each(headerCells, function () {\r\n            const cell" +
" = $(this);\r\n            members.push(cell.html());\r\n        });\r\n\r\n        cont" +
"ents += members.join(\",\");\r\n        members = [];\r\n        contents += \"\\n\";\r\n\r\n" +
"        $.each(rows, function () {\r\n            const row = $(this);\r\n          " +
"  const cells = row.find(\"td\");\r\n\r\n            $.each(cells, function () {\r\n    " +
"            const cell = $(this);\r\n\r\n                members.push(cell.html());\r" +
"\n            });\r\n\r\n            contents += members.join(\",\");\r\n            cont" +
"ents += \"\\n\";\r\n            members = [];\r\n        });\r\n\r\n        return contents" +
";\r\n    };\r\n\r\n\r\n    $(document).ready(function() {\r\n        const text = getTable" +
"InText();\r\n        const href = `data:text/plain;charset=utf-8,${encodeURICompon" +
"ent(text)}`;\r\n        $(\".download.button\").attr(\"href\", href);\r\n    });\r\n</scri" +
"pt>");

        }
    }
}
#pragma warning restore 1591
