#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
    using Frapid.ApplicationState.Cache;
    
    #line default
    #line hidden
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/OpeningCash/Index.cshtml")]
    public partial class _Views_Tasks_OpeningCash_Index_cshtml : System.Web.Mvc.WebViewPage<MixERP.Sales.ViewModels.OpeningCash>
    {
        public _Views_Tasks_OpeningCash_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
  
    ViewBag.Title = "title";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/validator.js\"");

WriteLiteral("></script>\r\n<style>\r\n    .very.relaxed.segment {\r\n        padding: 4em;\r\n    }\r\n<" +
"/style>\r\n<div");

WriteLiteral(" class=\"ui attached very relaxed segment\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">\r\n            BOD Cash\r\n            <div");

WriteLiteral(" class=\"ui teal label\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
                                  Write(DateTime.Now.ToLongDateString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"ui positive message\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
       Write(AppUsers.GetCurrent().Name);

            
            #line default
            #line hidden
WriteLiteral(", you may also edit the beginning cash later <a");

WriteLiteral(" href=\"eod\"");

WriteLiteral(">this evening</a>.\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"four fields\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Today\'s Beginning Cash</label>\r\n                   " +
" <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"AmountInputText\"");

WriteLiteral(" class=\"decimal\"");

WriteLiteral(" required=\"\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1060), Tuple.Create("\"", 1081)
            
            #line 31 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
               , Tuple.Create(Tuple.Create("", 1068), Tuple.Create<System.Object, System.Int32>(Model.Amount
            
            #line default
            #line hidden
, 1068), false)
);

WriteLiteral(" \r\n                           disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 32 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
                                                            Write(!Model.Closed);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" />\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Provided By</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProvidedByInputText\"");

WriteLiteral(" required=\"\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1355), Tuple.Create("\"", 1380)
            
            #line 36 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
   , Tuple.Create(Tuple.Create("", 1363), Tuple.Create<System.Object, System.Int32>(Model.ProvidedBy
            
            #line default
            #line hidden
, 1363), false)
);

WriteLiteral(" \r\n                           disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 37 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
                                                            Write(!Model.Closed);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"two fields\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                    <label>Memo</label>\r\n                    <textarea");

WriteLiteral(" id=\"MemoTextArea\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 43 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
                                                                                 Write(!Model.Closed);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
                                                                                                  Write(Model.Memo);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                </div>\r\n            </div>\r\n\r\n            <button");

WriteLiteral(" id=\"SaveButton\"");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" data-allow-edit=\"");

            
            #line 47 "..\..\Views\Tasks\OpeningCash\Index.cshtml"
                                                                                             Write(!Model.Closed);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(@">Save</button>
        </div>
    </div>
</div>

<script>
    (function () {
        const candidates = $(""[data-allow-edit]"");

        $.each(candidates, function () {
            const el = $(this);

            const allowEdit = el.attr(""data-allow-edit"").toLowerCase() === ""true"";
            el.prop(""disabled"", !allowEdit);
        });
    })();

    $(document).ready(function () {
        window.validator.initialize($("".ui.form""));
        $("".decimal"").number(true, window.currencyDecimalPlaces, ""."", """");
    });


    $(""#SaveButton"").unbind(""click"").bind(""click"", function () {
        function request(model) {
            const url = ""/dashboard/sales/tasks/opening-cash"";
            const data = JSON.stringify(model);

            return window.getAjaxRequest(url, ""POST"", data);
        };

        const confirmed = confirm(""Are you sure?"");

        if (!confirmed) {
            return;
        };

        const model = window.serializeForm($("".ui.form""));
        const ajax = request(model);

        ajax.success(function () {
            window.displaySuccess();
        });

        ajax.fail(function (xhr) {
            alert(JSON.stringify(xhr));
        });
    });
</script>");

        }
    }
}
#pragma warning restore 1591
