#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/PaymentTerms.cshtml")]
    public partial class _Views_Setup_PaymentTerms_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_PaymentTerms_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\PaymentTerms.cshtml"
  
    ViewBag.Title = "Payment Terms";
    Layout = ViewBag.SalesLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"P" +
"ayment Terms\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/sales/payment-term-scru" +
"d-view\";\r\n    scrudFactory.viewTableName = \"sales.payment_term_scrud_view\";\r\n\r\n " +
"   scrudFactory.formAPI = \"/api/forms/sales/payment-terms\";\r\n    scrudFactory.fo" +
"rmTableName = \"sales.payment_terms\";\r\n\r\n    scrudFactory.excludedColumns = [\"aud" +
"it_user_id\", \"audit_ts\"];\r\n\r\n    scrudFactory.allowDelete = true;\r\n    scrudFact" +
"ory.allowEdit = true;\r\n\r\n    scrudFactory.live = \"PaymentTermName\";\r\n\r\n    scrud" +
"Factory.card = {\r\n        header: \"payment_term_name\",\r\n        meta: \"payment_t" +
"erm_code\",\r\n        description: \"due_days\"\r\n    };\r\n\r\n    //scrudFactory.layout" +
" = [\r\n    //    {\r\n    //        tab: \"\",\r\n    //        fields: [\r\n    //      " +
"      [\"\", \"\"],\r\n    //            [\"\", \"\"],\r\n    //        ]\r\n    //    }\r\n    " +
"//];\r\n\r\n    scrudFactory.keys = [\r\n        {\r\n            property: \"DueFrequenc" +
"yId\",\r\n            url: \'/api/views/finance/frequencies/display-fields\',\r\n      " +
"      data: null,\r\n            valueField: \"Key\",\r\n            textField: \"Value" +
"\"\r\n        },\r\n        {\r\n            property: \"LateFeeId\",\r\n            url: \'" +
"/api/views/sales/late-fee/display-fields\',\r\n            data: null,\r\n           " +
" valueField: \"Key\",\r\n            textField: \"Value\"\r\n        },\r\n        {\r\n    " +
"        property: \"LateFeePostingFrequencyId\",\r\n            url: \'/api/views/fin" +
"ance/frequencies/display-fields\',\r\n            data: null,\r\n            valueFie" +
"ld: \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n\r\n\r\n    $.get(\'" +
"/ScrudFactory/View.html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.h" +
"tml\', function (form) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n       " +
"     $(\"#ScrudFactoryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/" +
"scrudfactory-view.js\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-for" +
"m.js\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
