#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Loyalty/Coupons/Index.cshtml")]
    public partial class _Views_Loyalty_Coupons_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Loyalty_Coupons_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Loyalty\Coupons\Index.cshtml"
  
    ViewBag.Title = "Discount Coupons";
    Layout = ViewBag.SalesLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"D" +
"iscount Coupons\";\r\n\r\n    scrudFactory.viewAPI = \"/api/forms/sales/coupons\";\r\n   " +
" scrudFactory.viewTableName = \"sales.coupons\";\r\n\r\n    scrudFactory.formAPI = \"/a" +
"pi/forms/sales/coupons\";\r\n    scrudFactory.formTableName = \"sales.coupons\";\r\n\r\n " +
"   scrudFactory.excludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n\r\n    scrudFac" +
"tory.allowDelete = true;\r\n    scrudFactory.allowEdit = true;\r\n\r\n    scrudFactory" +
".live = \"CouponCode\";\r\n\r\n    //scrudFactory.card = {\r\n    //    header: \"\",\r\n   " +
" //    description: \"\",\r\n    //    image: \"\"\r\n    //};\r\n\r\n    scrudFactory.layou" +
"t = [\r\n        {\r\n            tab: \"\",\r\n            fields: [\r\n                [" +
"\"GiftCardId\", \"\"]\r\n            ]\r\n        }\r\n    ];\r\n\r\n    scrudFactory.keys = [" +
"\r\n        {\r\n            property: \"AssociatedPriceTypeId\",\r\n            url: \'/" +
"api/forms/sales/price-types/display-fields\',\r\n            data: null,\r\n         " +
"   valueField: \"Key\",\r\n            textField: \"Value\"\r\n        },\r\n        {\r\n  " +
"          property: \"ForTicketOfPriceTypeId\",\r\n            url: \'/api/forms/sale" +
"s/price-types/display-fields\',\r\n            data: null,\r\n            valueField:" +
" \"Key\",\r\n            textField: \"Value\"\r\n        }\r\n    ];\r\n\r\n\r\n\r\n    $.get(\'/Sc" +
"rudFactory/View.html\', function (view) {\r\n        $.get(\'/ScrudFactory/Form.html" +
"\', function (form) {\r\n            $(\"#ScrudFactoryView\").html(view);\r\n          " +
"  $(\"#ScrudFactoryForm\").html(form);\r\n            $.cachedScript(\"/assets/js/scr" +
"udfactory-view.js\");\r\n            $.cachedScript(\"/assets/js/scrudfactory-form.j" +
"s\");\r\n        });\r\n    });\r\n</script>\r\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>\r\n\r\n<script>\r\n    $(document).on(\"formready\", function () {\r\n        $(\"#c" +
"ustomer_id\").change(function () {\r\n            function request(customerId) {\r\n " +
"               const url = \'/api/forms/inventory/customers/get-where/1\';\r\n\r\n    " +
"            const filters = [];\r\n                filters.push(window.getAjaxColu" +
"mnFilter(\"WHERE\", \"customer_id\", \"int\", window.FilterConditions.IsEqualTo, custo" +
"merId));\r\n                const data = JSON.stringify(filters);\r\n\r\n             " +
"   return window.getAjaxRequest(url, \"POST\", data);\r\n            };\r\n\r\n         " +
"   function setValueByElementId(elementId, value) {\r\n                const el = " +
"$(\"#\" + elementId);\r\n                const currentValue = el.val();\r\n           " +
"     if (!currentValue) {\r\n                    el.val(value);\r\n                }" +
";\r\n            };\r\n\r\n            const customerId = $(this).val();\r\n\r\n          " +
"  const ajax = request(customerId);\r\n\r\n            ajax.success(function (respon" +
"se) {\r\n                if (!response || !response[0]) {\r\n                    ret" +
"urn;\r\n                };\r\n\r\n                const model = response[0];\r\n\r\n      " +
"          setValueByElementId(\"first_name\", model.contact_first_name);\r\n        " +
"        setValueByElementId(\"middle_name\", model.contact_middle_name);\r\n        " +
"        setValueByElementId(\"last_name\", model.contact_last_name);\r\n            " +
"    setValueByElementId(\"address_line_1\", model.contact_address_line_1);\r\n      " +
"          setValueByElementId(\"address_line_2\", model.contact_address_line_2);\r\n" +
"                setValueByElementId(\"street\", model.contact_street);\r\n          " +
"      setValueByElementId(\"city\", model.contact_city);\r\n                setValue" +
"ByElementId(\"state\", model.contact_state);\r\n                setValueByElementId(" +
"\"country\", model.contact_country);\r\n                setValueByElementId(\"po_box\"" +
", model.contact_po_box);\r\n                setValueByElementId(\"zipcode\", model.c" +
"ontact_zipcode);\r\n                setValueByElementId(\"phone_numbers\", model.con" +
"tact_phone_numbers);\r\n                setValueByElementId(\"fax\", model.contact_f" +
"ax);\r\n            });\r\n        });\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
