#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Sales;
    
    #line 1 "..\..\Views\Tasks\Return\New.cshtml"
    using MixERP.Sales.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Return/New.cshtml")]
    public partial class _Views_Tasks_Return_New_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Return_New_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Return\New.cshtml"
  
    ViewBag.Title = "Sales Entries";
    Layout = ViewBag.SalesLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style>\r\n    .sales.return.header {\r\n        color: #eee;\r\n        font-size:" +
" 2em;\r\n    }\r\n</style>\r\n");

            
            #line 15 "..\..\Views\Tasks\Return\New.cshtml"
Write(Html.PartialView("Shared/POSScreen.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n\r\n    const transactionMasterId = window.getQueryStringByName(\"Tran" +
"sactionMasterId\");\r\n    const header = $(\"<div class=\'ui centered sales return h" +
"eader\'>Sales Return #<span></span></a>\");\r\n    header.find(\"span\").html(transact" +
"ionMasterId);\r\n    $(\".status.head\").before(header);\r\n\r\n    function removeEls()" +
" {\r\n        $(\".pos.tabs\").remove();\r\n        $(\"[data-payment-type]\").remove();" +
"\r\n        $(\".payment.type.container\").remove();\r\n        $(\".coupon.code.item\")" +
".parent().remove();\r\n        $(\".reprint.ticket.item\").remove();\r\n        $(\"#Sh" +
"ipperSelect\").closest(\".one.summary.items\").remove();\r\n    };\r\n\r\n    removeEls()" +
";\r\n\r\n    $(document).on(\"posready\", function () {\r\n        $(\"#CheckoutButton\")." +
"unbind(\"click\").bind(\"click\", function() {\r\n            function request(model) " +
"{\r\n                const url = \"/dashboard/sales/tasks/return/new\";\r\n           " +
"     const data = JSON.stringify(model);\r\n                return window.getAjaxR" +
"equest(url, \"POST\", data);\r\n            };\r\n\r\n            const model = window.g" +
"etModel();\r\n            model.TransactionMasterId = window.getQueryStringByName(" +
"\"TransactionMasterId\");\r\n\r\n\r\n            if (!model.Details.length) {\r\n         " +
"       window.displayMessage(\"Please select an item.\");\r\n                return;" +
"\r\n            };\r\n\r\n            const confirmed = confirm(\"Are you sure\");\r\n\r\n  " +
"          if (!confirmed) {\r\n                return;\r\n            };\r\n\r\n\r\n      " +
"      $(\"#CheckoutButton\").addClass(\"loading\");\r\n\r\n            const ajax = requ" +
"est(model);\r\n\r\n            ajax.success(function (response) {\r\n                c" +
"onst id = response;\r\n                document.location = \"/dashboard/sales/tasks" +
"/return\";\r\n            });\r\n\r\n            ajax.fail(function (xhr) {\r\n          " +
"      $(\"#CheckoutButton\").removeClass(\"loading\");\r\n                window.displ" +
"ayMessage(JSON.stringify(xhr));\r\n            });\r\n        });\r\n    })\r\n</script>" +
"");

        }
    }
}
#pragma warning restore 1591
